### ISSUE TITLE
Failing examples

### ISSUE THREAD

**Issue by bilderbuchi** [chriskiehl/Gooey#130]
on current master, I get the following failing examples:

error_exampe fails with AttributeError: 'Namespace' object has no attribute 'countdown':

```
Traceback (most recent call last):
  File "error_demo.py", line 47, in <module>
    main()
  File "/home/bilderbuchi/Dropbox/Coding/Gooey/gooey/python_bindings/gooey_decorator.py", line 77, in <lambda>
    return lambda: func()
  File "error_demo.py", line 28, in main
    print args.countdown
AttributeError: 'Namespace' object has no attribute 'countdown'
```

minimal_demo fails with

```
$ python minimal_demo.py 
Writing Build Config to: /home/bilderbuchi/Dropbox/Coding/Gooey/gooey/examples/gooey_config.json
Traceback (most recent call last):
  File "minimal_demo.py", line 18, in <module>
    main()
  File "/home/bilderbuchi/Dropbox/Coding/Gooey/gooey/python_bindings/gooey_decorator.py", line 71, in inner2
    return payload(*args, **kwargs)
  File "minimal_demo.py", line 13, in main
    args = parser.parse_args()
  File "/home/bilderbuchi/Dropbox/Coding/Gooey/gooey/python_bindings/gooey_decorator.py", line 65, in run_gooey
    f.write(json.dumps(build_spec, indent=2))
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/bilderbuchi/anaconda3/envs/py2/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <built-in function max> is not JSON serializable
```

The japanes and russian examples all have no text anywhere, but I don't know what to expect here, I haven't installed any language packs or whatever.

Also, most (or all I've encountered) of the buttons are not high enough for their label text, approx. the bottom half is missing. This is on Ubuntu 15.10.

**Comment by chriskiehl** [comment]
Hey @bilderbuchi, 

Those demos in the Gooey source were left in there by accident (and laziness). I've since removed them. The "Official" demos are in their own repo here: https://github.com/chriskiehl/GooeyExamples. They should all be working : ) 

Could you post a screenshot of the buttons? Wx renders a little wonky across the different platforms. However, I haven't seen it missing text.

**Comment by bilderbuchi** [comment]
> The "Official" demos are in their own repo here

hm, interesting/surprising choice. Thanks for the pointer!

Button screenshots (using the official examples):
![screenshot from 2015-12-24 12-13-00](https://cloud.githubusercontent.com/assets/327442/11993978/d68110e2-aa37-11e5-9ddc-f1bdbeb1fa06.png)

![screenshot from 2015-12-24 12-15-26](https://cloud.githubusercontent.com/assets/327442/11994006/2396ea78-aa38-11e5-8564-a0e8fe10832e.png)
