### ISSUE TITLE
AttributeError: 'BaseWindow' object has no attribute 'build_spec'

### ISSUE THREAD

**Issue by jfroco** [chriskiehl/Gooey#142]
I've got this when running progress bar examples:

```
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <l
ambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Users\jfroco\Envs\yt1\lib\site-packages\gooey\gui\windows\base_window
.py", line 201, in UpdateProgressBar
    if self.build_spec["disable_progress_bar_animation"] \
AttributeError: 'BaseWindow' object has no attribute 'build_spec'
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\wx-3.0-msw\wx\_core.py", line 16766, in <l
ambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Users\jfroco\Envs\yt1\lib\site-packages\gooey\gui\windows\base_window
.py", line 201, in UpdateProgressBar
    if self.build_spec["disable_progress_bar_animation"] \
AttributeError: 'BaseWindow' object has no attribute 'build_spec'

```

If I update line 201 from:

```
if self.build_spec["disable_progress_bar_animation"] \
           and sys.platform.startswith("win"):
```

to:

```
if sys.platform.startswith("win"):
```

it works as expected.

**Comment by chriskiehl** [comment]
Doh! Vestigial code.. thanks for the report. Will fix shortly.

**Comment by chriskiehl** [comment]
Fixed!
