### ISSUE TITLE
Gooey Parser throwing error when importing in Python 2.6

### ISSUE THREAD

**Issue by ragarwal86** [chriskiehl/Gooey#146]
Hi,

I was trying to use Gooey but it through error when I import it in Python2.6 . 
Below are the environment details:

OS: Centos 6
Pyhton : Version 2.6
Error:

> > > import Gooey

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ImportError: No module named Gooey

> > > import Gooey

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ImportError: No module named Gooey

> > > from gooey import Gooey, GooeyParser

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/usr/lib/python2.6/site-packages/gooey/**init**.py", line 2, in <module>

```
from gooey.python_bindings.gooey_decorator import Gooey
```

  File "/usr/lib/python2.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 14, in <module>

```
from gooey.gui import application
```

  File "/usr/lib/python2.6/site-packages/gooey/gui/application.py", line 8, in <module>

```
from gooey.gui.controller import Controller
```

  File "/usr/lib/python2.6/site-packages/gooey/gui/controller.py", line 2, in <module>

```
from gooey.gui.presenter import Presenter
```

  File "/usr/lib/python2.6/site-packages/gooey/gui/presenter.py", line 3, in <module>

```
from gooey.gui.processor import ProcessController
```

  File "/usr/lib/python2.6/site-packages/gooey/gui/processor.py", line 81

```
_locals = {k: safe_float(v) for k, v in match.groupdict().items()}

                              ^
```

SyntaxError: invalid syntax

 Is Gooey not supported by 2.6 ? Is there any alternative to it?

**Comment by chriskiehl** [comment]
Looks like it's exploding due to the dict comprehension, which [doesn't exist in 2.6](https://www.python.org/download/releases/2.7/). 

No chance of using a more modern version of Python? ; )

**Comment by chriskiehl** [comment]
Closing. 

Testing Gooey across three different operating systems and two major Python versions is an extremely painful process. I'm going to go ahead and call everything before 2.7 unsupported : /
