### ISSUE TITLE
1st example from python.org/2/library/argparse.html does not work

### ISSUE THREAD

**Issue by drandreaskrueger** [chriskiehl/Gooey#147]
I am learning Gooey, and argparse.

The first [example from argparse.html](https://docs.python.org/2/library/argparse.html#example) does not work:

    import argparse
    from gooey import Gooey
    
    @Gooey
    def main():
        
        parser = argparse.ArgumentParser(description='Process some integers.')
        parser.add_argument('integers', metavar='N', type=int, nargs='+',
                           help='an integer for the accumulator')
        parser.add_argument('--sum', dest='accumulate', action='store_const',
                           const=sum, default=max,
                           help='sum the integers (default: find the max)')
        
        args = parser.parse_args()
        print args.accumulate(args.integers)
      
    if __name__=="__main__":
        main()

These are the errors I get:

	Traceback (most recent call last):
	  File "testArgparse.py", line 24, in <module>
		main()
	  File "gooey-0.9.2-py2.7.egg\gooey\python_bindings\gooey_decorator.py", line 71, in inner2
		return payload(*args, **kwargs)
	  File "testArgparse.py", line 20, in main
		args = parser.parse_args()
	  File "gooey-0.9.2-py2.7.egg\gooey\python_bindings\gooey_decorator.py", line 66, in run_gooey
		application.run(build_spec)
	  File "gooey-0.9.2-py2.7.egg\gooey\gui\application.py", line 19, in run
		controller = Controller(build_spec)
	  File "gooey-0.9.2-py2.7.egg\gooey\gui\controller.py", line 12, in __init__
		self.presentation.initialize_view()
	  File "gooey-0.9.2-py2.7.egg\gooey\gui\presenter.py", line 65, in initialize_view
		self.syncronize_from_model()
	  File "gooey-0.9.2-py2.7.egg\gooey\gui\presenter.py", line 81, in syncronize_from_model
		widget.set_value(self.model.optional_args[index]._value)
	  File "gooey-0.9.2-py2.7.egg\gooey\gui\widgets\components.py", line 155, in set_value
		self.widget.SetValue(val)
	  File "wx-3.0-msw\wx\_controls.py", line 392, in SetValue
		return _controls_.CheckBox_SetValue(*args, **kwargs)
	TypeError: in method 'CheckBox_SetValue', expected argument 2 of type 'bool'

**Comment by drandreaskrueger** [comment]
same example as https://github.com/chriskiehl/Gooey/issues/39 but different Exception

**Comment by drandreaskrueger** [comment]
Windows 7 

    import wx
    wx.__version__
    '3.0.0.0'

**Comment by chriskiehl** [comment]
@drandreaskrueger 

Thanks for all the debug info, and for the patience while waiting for my slow response. 

So, this is an unfortunate bug (doubly so being that it is the _first_ example in the `argparse` docs). In short, it's failing because a function reference is being stored in the `const` and `default` fields for the `sum` argument. This confuses the Gooey. 

Will fix shortly.

**Comment by drandreaskrueger** [comment]
Thanks a lot. Happy to be patient. Your tool is so helpful, great!

**Comment by chriskiehl** [comment]
Thanks for your patience! 

Fix is in master and on PyPi.
