### ISSUE TITLE
IOError: Could not find english language file after converting script to exe using py2exe

### ISSUE THREAD

**Issue by mistrics** [chriskiehl/Gooey#19]
Hi,

I have made a small script that is using Gooey and when I converted it to a exe using py2exe or pythonInstaller I am getting following problem.

Traceback (most recent call last):
  File "command_ui.py", line 1, in <module>
  File "gooey\__init__.pyc", line 1, in <module>
  File "gooey\gooey_decorator.pyc", line 16, in <module>
  File "gooey\gui\base_window.pyc", line 16, in <module>
  File "gooey\gui\header.pyc", line 10, in <module>
  File "gooey\i18n.pyc", line 37, in <module>
  File "gooey\i18n.pyc", line 24, in get_path
IOError: Could not find english language file

**Comment by chriskiehl** [comment]
Closing this. Super old and no longer sure if even relevant. Plus, PyInstaller and cxFreeze have since emerged as the preferred ways of packaging Gooey. 

* https://github.com/chriskiehl/Gooey/issues/58
* http://chriskiehl.com/article/packaging-gooey-with-pyinstaller/
