### ISSUE TITLE
Error when using metavar with nargs

### ISSUE THREAD

**Issue by carlfischerjba** [chriskiehl/Gooey#199]
The test below requests two integers and adds them up. When using argparse, I use a tuple metavar to name each value so the user can tell that they represent different things. Gooey doesn't like this and raises a `TypeError` in `components.py:format_title()`. Using a GooeyParser doesn't help. Replacing the metavar tuple with a single string works. 

Could we tweak the `format_title` method to accept a tuple of strings?

```lang=python
from argparse import ArgumentParser
from gooey import Gooey
    
@Gooey
def main_argparse():
    parser = ArgumentParser(description='Sum two integers.')
    parser.add_argument('integers', type=int, nargs=2, metavar=('first', 'second'))
    
    args = parser.parse_args()
    print sum(args.integers)
        
if __name__=="__main__":
    #main_argparse()
    main_gooey()
```

**Comment by jschultz** [comment]
More generally, there are a few cases involving `nargs` that Gooey does not currently handle but would not be too complicated. Looking at the code, the only reference to `nargs` seems to be about whether or not to put quotes around the argument - it's not clear to me what this is about but presumably it serves some purpose. One key thing that doesn't work is optional positional arguments (`nargs` = `'*'` or '`?'`) - Gooey treats such arguments as required. While acknowledging the difficulty of implementing variable numbers of arguments as discussed in #59, it seems feasible enough to implement a fixed number of arguments (`nargs` equal to some integer) and optional positional arguments.

**Comment by pawamoy** [comment]
Indeed, just saw that `nargs="*"` becomes required in Gooey.

**Comment by Dobatymo** [comment]
Same problem here. Traceback:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 124, in inner2
    return payload(*args, **kwargs)
  File "<stdin>", line 7, in main_argparse
  File "C:\Program Files\Python37\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 119, in run_gooey
    application.run(build_spec)
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\application.py", line 21, in run
    app, _ = build_app(build_spec)
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\application.py", line 30, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\containers\application.py", line 43, in __init__
    self.configs = self.buildConfigPanels(self)
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\containers\application.py", line 223, in buildConfigPanels
    for widgets in self.buildSpec['widgets'].values()]
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\containers\application.py", line 223, in <listcomp>
    for widgets in self.buildSpec['widgets'].values()]
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\components\config.py", line 16, in __init__
    self.layoutComponent()
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\components\config.py", line 92, in layoutComponent
    self.makeGroup(self, sizer, item, 0, wx.EXPAND | wx.ALL, 10)
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\components\config.py", line 136, in makeGroup
    widget = self.reifyWidget(parent, item)
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\components\config.py", line 188, in reifyWidget
    return widgetClass(parent, item)
  File "C:\Program Files\Python37\lib\site-packages\gooey\gui\components\widgets\bases.py", line 50, in __init__
    self.label = wx.StaticText(self, label=widgetInfo['data']['display_name'])
TypeError: StaticText(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 'label' has unexpected type 'tuple'
```

**Comment by clausjuhl** [comment]
Same problem here.

**Comment by albertma1986** [comment]
Same :)
