### ISSUE TITLE
Exception raised while installing 0.9.5.2 from Pypi.

### ISSUE THREAD

**Issue by KelSolaar** [chriskiehl/Gooey#233]
Using `pip install --no-dependencies --ignore-installed --install-option="--prefix=D:\Packages\gooey" gooey` the following exception is being raised:

``` python
Collecting gooey
  Using cached Gooey-0.9.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\thomas\appdata\local\temp\pip-build-ffltlx\gooey\setup.py", line 9, in <module>
        with open('version.txt', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'version.txt'
```

**Comment by chriskiehl** [comment]
Resolved in the 1.0 version on PyPi. 

`pip install -U gooey` will cure what ails ya
