### ISSUE TITLE
 'NoneType' object is not callable

### ISSUE THREAD

**Issue by mroswell** [chriskiehl/Gooey#257]
Hello There, Future Issue Creator! 
 - [x ] OS mac
 - [x ] Python Version - Python 2.7.14 :: Anaconda, Inc.
 - [ ] Gooey Version  (how to find this?)
 - [x ] Thorough description of problem 

Excerpt of terminal output after running
```
python setup.py install
```
```
To check the build, run the selftest.py script.

Copying Pillow-5.0.0-py2.7-macosx-10.6-x86_64.egg to /Users/mr/anaconda2/lib/python2.7/site-packages
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/mr/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/mr/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mr/anaconda2/lib/python2.7/multiprocessing/pool.py", line 332, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/mr/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/mr/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mr/anaconda2/lib/python2.7/multiprocessing/pool.py", line 370, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable


Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
Adding Pillow 5.0.0 to easy-install.pth file

Installed /Users/mr/anaconda2/lib/python2.7/site-packages/Pillow-5.0.0-py2.7-macosx-10.6-x86_64.egg
Finished processing dependencies for Gooey==1.0.0
```
Was this a successful installation? (It doesn't look like it...) By the way, I can't find the selftest.py referenced in the message above.

**Comment by mroswell** [comment]
i found

https://anaconda.org/anaconda/pillow

and ran
```
conda install -c anaconda pillow 
```
And didn't get that error any more. I look forward to trying gooey!
