### ISSUE TITLE
No matching distribution found for wx

### ISSUE THREAD

**Issue by mroswell** [chriskiehl/Gooey#258]
- [x ] OS - Mac
 - [ x ] Python Version - Python 2.7.14 :: Anaconda, Inc.
 - [ ] Gooey Version - How to determine?
 - [x ] Thorough description of problem 
```
$ python xls2xml.py
Traceback (most recent call last):
  File "xls2xml.py", line 5, in <module>
    from gooey import Gooey
  File "/Users/mr/advocacy/kobo/Gooey/gooey/__init__.py", line 2, in <module>
    from gooey.python_bindings.gooey_decorator import Gooey
  File "/Users/mr/advocacy/kobo/Gooey/gooey/python_bindings/gooey_decorator.py", line 14, in <module>
    from gooey.gui import application
  File "/Users/mr/advocacy/kobo/Gooey/gooey/gui/application.py", line 5, in <module>
    import wx
ImportError: No module named wx
marjorieroswell (master) Gooey $ pip install wx
Collecting wx
  Could not find a version that satisfies the requirement wx (from versions: )
No matching distribution found for wx

```

**Comment by mroswell** [comment]
installing
```
brew install wxpython
```
as described here: https://stackoverflow.com/questions/9205317/how-do-i-install-wxpython-on-mac-os-x
didn't fix the ImportError issue

looks like 
```
$ conda install wxpython 
```
installed something, and now I get no error upon running
$ python xls2xml.py
But now nothing happened. I was expecting some sort of UI to come up.

I've imported Gooey and added the decorator above def main():
I guess there's more for me to understand here. Probably that I need to learn argparse, rather than sys.argv...

**Comment by mroswell** [comment]
Sorry. I see the directions mention this extra install requirement. Will close
