### ISSUE TITLE
Add shell=True to gooey/gui/seeder.py

### ISSUE THREAD

**Issue by edjw** [chriskiehl/Gooey#261]
- MacOS 10.13.3
 - Python 3 and 2
 - Gooey 1.0.0
 
Tried to run [dynamic_updates.py](https://github.com/chriskiehl/GooeyExamples/blob/master/examples/dynamic_updates.py) from the GooeyExamples repository as mentioned [here](https://github.com/chriskiehl/GooeyExamples/issues/10). Tracebacks from Python 3 and 2 at the bottom of this.

The issue was fixed by adding `, shell=True` to line 15 of `gooey/gui/seeder.py` to make it look like this below:

`proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)`

Python3

```
Traceback (most recent call last):
  File "dynamic_updates.py", line 110, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 83, in inner2
    return payload(*args, **kwargs)
  File "dynamic_updates.py", line 53, in main
    args = parser.parse_args()
  File "/usr/local/lib/python3.6/site-packages/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/usr/local/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 65, in __init__
    self.fetchExternalUpdates()
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 150, in fetchExternalUpdates
    self.buildSpec['encoding']
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/seeder.py", line 15, in fetchDynamicProperties
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "'/usr/local/opt/python3/bin/python3.6' -u 'dynamic_updates.py' gooey-seed-ui --ignore-gooey": "'/usr/local/opt/python3/bin/python3.6' -u 'dynamic_updates.py' gooey-seed-ui --ignore-gooey"
```

Python 2

```
Traceback (most recent call last):
  File "dynamic_updates.py", line 108, in <module>
    main()
  File "/Library/Python/2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 83, in inner2
    return payload(*args, **kwargs)
  File "dynamic_updates.py", line 53, in main
    args = parser.parse_args()
  File "/Library/Python/2.7/site-packages/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/Library/Python/2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/Library/Python/2.7/site-packages/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/Library/Python/2.7/site-packages/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/Library/Python/2.7/site-packages/gooey/gui/containers/application.py", line 65, in __init__
    self.fetchExternalUpdates()
  File "/Library/Python/2.7/site-packages/gooey/gui/containers/application.py", line 150, in fetchExternalUpdates
    self.buildSpec['encoding']
  File "/Library/Python/2.7/site-packages/gooey/gui/seeder.py", line 15, in fetchDynamicProperties
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by iref** [comment]
Same error happened to me on Ubuntu 18.04 LTS with Python 3.6.5 and Gooey 1.0.0.

**Comment by edjw** [comment]
You can try this @iref 

> The issue was fixed by adding , shell=True to line 15 of gooey/gui/seeder.py to make it look like this below:

> proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)

**Comment by iref** [comment]
Thank you. Is there a way how to pass this option to seeder.py or do i have to add it to source file and republish package locally?

**Comment by edjw** [comment]
I did it locally. Not sure if there's an option to pass it to seeder.py I'm afraid

**Comment by iref** [comment]
Okey, thanks for help again. I'll look into it.

**Comment by Madoshakalaka** [comment]
@chriskiehl any followup? This fix is still not in the master branch
