### ISSUE TITLE
 No module named 'gooey.gui.components.menubar' for 1.0.2-release branch

### ISSUE THREAD

**Issue by Aikhjarto** [chriskiehl/Gooey#339]
I tried the 1.0.2-release branch and cannot import gooey because of a missing sub-module 'gooey.gui.components.menubar'.

### Appropriate fields from the issue template
 - OS: Windows 7
 - Python Version: 3.6
 - Gooey Version: 1.0.2-release branch
 - Expected Behavior: gooey can be imported
 - Actual Behavior: crash with "No module named 'gooey.gui.components.menubar'" at import

### Traceback
```
import gooey
Traceback (most recent call last):

  File "<ipython-input-3-70afb8e03893>", line 1, in <module>
    import gooey

  File "(...long path...)\site-packages\gooey\__init__.py", line 2, in <module>
    from gooey.python_bindings.gooey_decorator import Gooey

  File "(...long path...)\site-packages\gooey\python_bindings\gooey_decorator.py", line 14, in <module>
    from gooey.gui import application

  File "(...long path...)\site-packages\gooey\gui\application.py", line 10, in <module>
    from gooey.gui.containers.application import GooeyApplication

  File "(...long path...)\site-packages\gooey\gui\containers\application.py", line 17, in <module>
    from gooey.gui.components.menubar import MenuBar

ModuleNotFoundError: No module named 'gooey.gui.components.menubar'
```

### Minimal crashing example
```python
import gooey
````

**Comment by chriskiehl** [comment]
lol. That minimal example. 

I got a little sloppy with my commits there. #267 is in progress and apparently bled into an unrelated commit. 

Some rebasing will happen shortly to clean that all up.

**Comment by chriskiehl** [comment]
Resolved! https://github.com/chriskiehl/Gooey/commit/73b08c126a64164c6ddcfa7114024ed4336dc3f1 And that branch now has Menu Bars! Check 'em out! ^_^
