### ISSUE TITLE
enable load_build_config gives TypeError: environment can only contain strings

### ISSUE THREAD

**Issue by TurBoss** [chriskiehl/Gooey#375]
- OS Windows 10
- Python Version 2.7
- Gooey Version 1.02
when I add the decorator option 
       load_build_config="gooey_config.json",

I get this error
```

Traceback (most recent call last):
  File "C:\Users\TurBoss\Projetcs\springrts_smf_compiler\venv\lib\site-packages\wx\core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Users\TurBoss\Projetcs\springrts_smf_compiler\venv\lib\site-packages\gooey\gui\containers\application.py", line 79, in onStart
    self.clientRunner.run(self.buildCliString())
  File "C:\Users\TurBoss\Projetcs\springrts_smf_compiler\venv\lib\site-packages\gooey\gui\processor.py", line 54, in run
    stderr=subprocess.STDOUT, shell=True, env=env)
  File "C:\Python27\Lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 644, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

Thanks!

**Comment by TurBoss** [comment]
could be posible to have save/load buttons??
Thanks!

**Comment by TurBoss** [comment]
tested on 1.03.release

**Comment by chriskiehl** [comment]
Please fill out the issue template in its entirety. A code sample helps with debugging
