### ISSUE TITLE
[TypeError: cannot serialize '_io.TextIOWrapper' object] when using [metavar='<FILE>', type=argparse.FileType()].

### ISSUE THREAD

**Issue by changeling** [chriskiehl/Gooey#377]
- OSX Mojave
 - Python 3.7.2
 - Gooey 1.0.2
 - Expected behavior: Handling of FileType. 
 - Actual Behavior: `TypeError: cannot serialize '_io.TextIOWrapper' object`

 - Minimal code example:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Minimal example for [metavar='<FILE>', type=argparse.FileType()] issue.

NOTE: Same behavior when `GooeyParser` replaces `argparse.ArgumentParser`.
NOTE: Behavior is independent of `FileType()` arguments:
        `FileType('w', encoding='UTF-8')` and
        `FileType()` yield same failure.
"""

# global import
import sys
import argparse

try:
    from gooey import Gooey
except ImportError:
    sys.stderr.write('You need to install the gooey module first\n')
    sys.stderr.write('("python3 -m pip install gooey"\n')
    exit(2)


@Gooey
def main():
    """Demonstrate [metavar='<FILE>', type=argparse.FileType()] issue."""
    parser = argparse.ArgumentParser(
        description="Show [metavar='<FILE>', type=argparse.FileType()] issue.",
        add_help=False,
        usage="test.py -u username -p password [options]")
    parser.add_argument('-u',
                        metavar='<STR>', type=str, help='Username')
    parser.add_argument('-p', metavar='<STR>', type=str, help='Password')
    try:
        parser.add_argument('-o',
                            metavar='<FILE>',
                            type=argparse.FileType('w', encoding='UTF-8'),
                            default=sys.stdout,
                            help='output data file [stdout]')
        parser.add_argument('-l',
                            metavar='<FILE>',
                            type=argparse.FileType('w', encoding='UTF-8'),
                            default=sys.stderr,
                            help='output log file [stderr]')
    except TypeError:
        sys.stderr.write(
            'Python >= 3.4 is required to run this script\n')
        sys.stderr.write(
            '(see https://docs.python.org/3/whatsnew/3.4.html#argparse)\n')
        exit(2)

    args = parser.parse_args()


if __name__ == '__main__':
    main()
```

**Comment by changeling** [comment]
Digging in to try and get my head around this, I learned that deepcopy has issues with complex objects. The following seems directly on target:

[Why does deepcopy fail when copying a complex object](https://stackoverflow.com/questions/32593035/why-does-deepcopy-fail-when-copying-a-complex-object)

> copy.deepcopy's behavior for classes that don't provide direct support (by defining __deepcopy__) is to pickle then unpickle the object to ensure a new instance is created.
> ...
> The error comes because the object you're copying contains io.TextIOWrapper, and the serialization fails.

**Comment by changeling** [comment]
So here we go:

The issue results when a file handle is passed to `deepcopy` in `gooey/gui/application.py` with the `gapp` instance:

`gapp = GooeyApplication(merge(build_spec, imagesPaths))`.

If there's an action defined along the lines of:
`parser.add_argument('-o', metavar='<FILE>', type=argparse.FileType('w', encoding='UTF-8'), default=sys.stdout, help='output file [stdout]')`

that action passes a file handle into the mix.

The `merge()` function in `gooey/util/functional.py` creates the `copies` iterator, which raises the `TypeError` exception when the iterator is used in the `reduce()` call of the `return` statement.

You can see this happen with the following:
```
def merge(*maps, print_str=None):
    """Merge all maps left to right"""
    copies = map(deepcopy, maps)
    print(*copies)
    return reduce(lambda acc, val: acc.update(val) or acc, copies)
```

The exception is raised when the `print()` statement calls the `copies` iterator, before the `reduce()` is returned.

And `deepcopy` just hates file handles.

**Comment by chriskiehl** [comment]
Whoa -- interesting. I guess it has never occurred to me to pass stdin/out directly to `default` in that way. Most usage I've seen has been geared towards plain data (strings, lists, numbers) with the occasional function ref thrown in there (which we serialize down to its name).    

So, this is actually a bug in [`clean_default`](https://github.com/chriskiehl/Gooey/blob/1.0.3-release/gooey/python_bindings/argparse_to_json.py#L427), which is a function that has a long rich history of being bug-ridden and wrong. It accounts for `callable`'s, but doesn't account for general object instances.

The instance making its way all the way to the buildspec is the root of the problem here. Everything inside of the spec should be plain basic serializable json data (and thus workable by my bootleg merge function).

This is a quick fix. I'll have it ready in a few.

**Comment by chriskiehl** [comment]
Fix is here! https://github.com/chriskiehl/Gooey/commit/b3222a8279a0bbdbbcbdd59b904e720c8dfb5862 

Actually ends up finally closing (for real) Issue #147, which I apparently misunderstood all those years ago.. 

Here's a paired down version of your example: 

```python
import sys
import argparse
from gooey import Gooey


@Gooey
def main():
    """Demonstrate [metavar='<FILE>', type=argparse.FileType()] issue."""
    parser = argparse.ArgumentParser(
        description="Show [metavar='<FILE>', type=argparse.FileType()] issue.",
        add_help=False,
        usage="test.py -u username -p password [options]")
    parser.add_argument('-o',
                        metavar='<FILE>',
                        type=argparse.FileType('w'),
                        default=sys.stdout,
                        help='output data file [stdout]')

    args = parser.parse_args()
    print(args.o)
    for i in range(10):
        args.o.write(str(i))


if __name__ == '__main__':
    main()
```

It now has the expected behavior. Doing nothing dumps things to `stdout`, adding a destination dumps it to disk. 

Give it a whirl and lemme know if I missed anything.

**Comment by changeling** [comment]
Tried it briefly with the project that originally triggered the error, and
now I end up with:

```
Traceback (most recent call last):
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 49, in OnSize
    self.Wrap(event.GetSize().width)
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 72, in Wrap
    text = wordwrap(self.label, width, dc)
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/lib/python3.7/site-packages/wx/lib/wordwrap.py",
line 29, in wordwrap
    - max([0] + [pte[i]-pte[i-1] for i in range(1,len(pte))]) )
RecursionError: maximum recursion depth exceeded while calling a Python
object
Traceback (most recent call last):
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 49, in OnSize
    self.Wrap(event.GetSize().width)
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 72, in Wrap
    text = wordwrap(self.label, width, dc)
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/lib/python3.7/site-packages/wx/lib/wordwrap.py",
line 29, in wordwrap
    - max([0] + [pte[i]-pte[i-1] for i in range(1,len(pte))]) )
RecursionError: maximum recursion depth exceeded while calling a Python
object
Traceback (most recent call last):
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 49, in OnSize
    self.Wrap(event.GetSize().width)
RecursionError: maximum recursion depth exceeded while calling a Python
object
Traceback (most recent call last):
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 49, in OnSize
    self.Wrap(event.GetSize().width)
RecursionError: maximum recursion depth exceeded while calling a Python
object
Traceback (most recent call last):
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 49, in OnSize
    self.Wrap(event.GetSize().width)
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py",
line 71, in Wrap
    dc.SetFont(self.GetFont())
RecursionError: maximum recursion depth exceeded while calling a Python
object
```

Which launches the wx inspection tool. Exiting that yields:
```
Traceback (most recent call last):
  File "./getmyancestors.py", line 1005, in <module>
    main()
  File
"/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/python_bindings/gooey_decorator.py",
line 87, in inner2
    return payload(*args, **kwargs)
  File "./getmyancestors.py", line 925, in main
    if args.i:
AttributeError: 'NoneType' object has no attribute 'i'
```

Haven't had time to dig in yet, so this is a bit of a preliminary response.
Gotta get some sleep. :)

**Comment by changeling** [comment]
Tried it briefly with the project that originally triggered the error, and now I end up with:

```
Traceback (most recent call last):
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 49, in OnSize
    self.Wrap(event.GetSize().width)
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 72, in Wrap
    text = wordwrap(self.label, width, dc)
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/lib/python3.7/site-packages/wx/lib/wordwrap.py", line 29, in wordwrap
    - max([0] + [pte[i]-pte[i-1] for i in range(1,len(pte))]) )
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 49, in OnSize
    self.Wrap(event.GetSize().width)
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 72, in Wrap
    text = wordwrap(self.label, width, dc)
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/lib/python3.7/site-packages/wx/lib/wordwrap.py", line 29, in wordwrap
    - max([0] + [pte[i]-pte[i-1] for i in range(1,len(pte))]) )
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 49, in OnSize
    self.Wrap(event.GetSize().width)
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 49, in OnSize
    self.Wrap(event.GetSize().width)
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 49, in OnSize
    self.Wrap(event.GetSize().width)
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/gui/components/util/wrapped_static_text.py", line 71, in Wrap
    dc.SetFont(self.GetFont())
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "./getmyancestors.py", line 1005, in <module>
    main()
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/python_bindings/gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File "./getmyancestors.py", line 925, in main
    if args.i:
AttributeError: 'NoneType' object has no attribute 'i'
```

Which launches the wx inspection tool. Exiting that yields:

```
Traceback (most recent call last):
  File "./getmyancestors.py", line 1005, in <module>
    main()
  File "/Users/clarson/Desktop/getmyancestors-gooey/getmyancestors/venv/src/gooey/gooey/python_bindings/gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File "./getmyancestors.py", line 925, in main
    if args.i:
AttributeError: 'NoneType' object has no attribute 'i'
```

Haven't had time to dig in yet, so this is a bit of a preliminary response. Gotta get some sleep. :)
