### ISSUE TITLE
1.0.3 About Dialog Feature throws error

### ISSUE THREAD

**Issue by mariaeiou** [chriskiehl/Gooey#381]
First of all - thanks for developing this awesome package!

In issue #330 it was mentioned that there will be an About Dialog in the 1.0.2 release. Is it already implemented and available? And is there a documentation on how to use it? I would really love to have this feature working.

Thanks!

**Comment by chriskiehl** [comment]
Yep. Dialogs are implemented in the release branch here: https://github.com/chriskiehl/Gooey/tree/1.0.3-release#menus 

I need to carve out some time to actually get it released.. but in the mean time, you can pip install the branch and give it a test (which would actually be appreciated! Lemme know if you find bugs / functionality weirdness)

**Comment by mariaeiou** [comment]
I installed the branch (1.0.3-release) and tried the example from your documentation but I could not get the menu to work.

My environment:
- ubuntu 16.04 LTS
- python 2.7 (miniconda)

My code:

```
from gooey import Gooey
from gooey import GooeyParser

@Gooey(
    program_name='ICC-OBS Version 0.1',
    show_stop_warning=False,
    force_stop_is_error=False,
    disable_progress_bar_animation=True,
    required_cols=1,
    default_size=(1080, 1080),
    advanced=True,
    navigation='TABBED',
    image_dir=resource_path('images'),
	menu=[{
        'name': 'File',
        'items': [{
                'type': 'AboutDialog',
                'menuTitle': 'About',
                'name': 'Gooey Layout Demo',
                'description': 'An example of Gooey\'s layout flexibility',
                'version': '1.2.1',
                'copyright': '2018',
                'website': 'https://github.com/chriskiehl/Gooey',
                'developer': 'http://chriskiehl.com/',
                'license': 'MIT'
            }, {
                'type': 'MessageDialog',
                'menuTitle': 'Information',
                'caption': 'My Message',
                'message': 'I am demoing an informational dialog!'
            }, {
                'type': 'Link',
                'menuTitle': 'Get Data',
                'url': 'https://data.ccca.ac.at/group/climaproof'
            }]
        },{
        'name': 'Help',
        'items': [{
            'type': 'Link',
            'menuTitle': 'Documentation',
            'url': 'https://www.readthedocs.com/foo'
        }]
    }]
)
def main():
	parser = GooeyParser(description='Example About Dialoge')
	parser.add_argument('filename', help="name of the file to process") 
	args = parser.parse_args()

if __name__ == "__main__":
    main()

```

This results in the following error:

_Traceback (most recent call last):
  File "main_about_dialog.py", line 75, in <module>
    main()
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File "main_about_dialog.py", line 72, in main
    args = parser.parse_args()
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 82, in run_gooey
    application.run(build_spec)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/gui/application.py", line 16, in run
    app = build_app(build_spec)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/gui/application.py", line 25, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/gui/containers/application.py", line 45, in __init__
    self.console = Console(self, buildSpec)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/gui/components/console.py", line 21, in __init__
    self.textbox = BasicTextConsole(self)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/gui/components/widgets/basictextconsole.py", line 5, in __init__
    super().__init__(parent, -1, "", style=wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_RICH)
TypeError: super() takes at least 1 argument (0 given)_

**Comment by chriskiehl** [comment]
Ah, crud! Thanks for giving it a dry run. 

I'll get this patched up asap!

**Comment by chriskiehl** [comment]
OK, it was a backward compatibility issue with Python2.7, which doesn't like the way `super()` was used. 

Fixed here: https://github.com/chriskiehl/Gooey/commit/02ed319e5f30e23ef253ec5e350a4e34493c4fc2 

All should be working now. 

Reopen if you encounter anything else!

**Comment by mariaeiou** [comment]
Again I encounter an error when trying to run the same code mentioned above:

_Traceback (most recent call last):
  File "main_about_dialog.py", line 66, in <module>
    main()
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File "main_about_dialog.py", line 63, in main
    args = parser.parse_args()
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 75, in run_gooey
    **params)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/config_generator.py", line 106, in create_from_parser
    if build_spec['show_advanced']
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/argparse_to_json.py", line 101, in convert
    }) for name, sub_parser in iter_parsers(parser))
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/home/mariaw/miniconda2/envs/iccobs_test/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/argparse_to_json.py", line 101, in <genexpr>
    }) for name, sub_parser in iter_parsers(parser))
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/argparse_to_json.py", line 115, in process
    return categorize2(strip_empty(corrected_action_groups), widget_dict, options)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/argparse_to_json.py", line 247, in categorize2
    } for group in groups]
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/argparse_to_json.py", line 258, in categorize
    yield action_to_json(action, _get_widget(action, 'TextField'), options)
  File "/home/miniconda2/envs/iccobs_test/lib/python2.7/site-packages/gooey/python_bindings/argparse_to_json.py", line 280, in get_widget
    return supplied_widget or type_arg_widget or default
NameError: global name 'type_arg_widget' is not defined_

**Comment by chriskiehl** [comment]
arg.. this is due to a later [Pull Request](https://github.com/chriskiehl/Gooey/pull/386) that I didn't vet close enough before merging.. however, [it has since been fixed!](https://github.com/chriskiehl/Gooey/pull/387)

**Comment by mariaeiou** [comment]
Now it works perfectly! Thanks! :)

**Comment by mariaeiou** [comment]
Sorry to bother you again but there now seems to be another issue, that was not here before: there are suddenly several line breaks in the help-text for the different input fields - I can't find the reason for this behaviour.
Screenshot of my test-gui so you know what I mean (still using the same code):

![gooey_screenshot](https://user-images.githubusercontent.com/44156163/54201732-aabd5f80-44ce-11e9-9234-78ab6c800718.png)

**Comment by chriskiehl** [comment]
Please _keep_ 'bothering'! ^_^ Learning about these quirks now is way better than post release. 

I've copied this to a new issue so that it can be tracked separately: https://github.com/chriskiehl/Gooey/issues/395
