### ISSUE TITLE
Error running Gooey with argparse doc example

### ISSUE THREAD

**Issue by Djiit** [chriskiehl/Gooey#39]
Hi, 

I ran into this issue while just testing Gooey on the [Python doc argparse example](https://docs.python.org/2.7/library/argparse.html#example): 
```
icon = os.path.join(image_dir, "icon.ico")
__init__ = os.path.join(image_dir, "__init__.py")
__init__ = os.path.join(image_dir, "__init__.pyc")
loader = os.path.join(image_dir, "loader.gif")
images = os.path.join(image_dir, "images.jpg")
settings2 = os.path.join(image_dir, "settings2.png")
alessandro_rei_checkmark = os.path.join(image_dir, "alessandro_rei_checkmark.png")
computer = os.path.join(image_dir, "computer.png")
computer3 = os.path.join(image_dir, "computer3.png")
computer2 = os.path.join(image_dir, "computer2.png")
returning resized image
returning resized image
returning resized image
Traceback (most recent call last):
  File "whyd2/testtt.py", line 18, in <module>
    main()
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gooey_decorator.py", line 59, in inner
    frame = BaseWindow(BodyPanel, client_app, params)
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gui/base_window.py", line 44, in __init__
    self._init_components(BodyPanel)
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gui/base_window.py", line 67, in _init_components
    self.config_panel = BodyPanel(self)
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gui/advanced_config.py", line 38, in __init__
    self._do_layout()
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gui/advanced_config.py", line 59, in _do_layout
    self.AddWidgets(container, self.components.required_args, add_space=True)
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gui/advanced_config.py", line 79, in AddWidgets
    widget_group = component.Build(parent=self)
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gui/components.py", line 38, in Build
    self._msg = self.CreateHelpMsgWidget(parent, self._action)
  File "/home/jtanay/.virtualenvs/whyd2/lib/python2.7/site-packages/gooey/gui/components.py", line 67, in CreateHelpMsgWidget
    base_text.SetLabelText(base_text.GetLabelText() + self.CreateNargsMsg(action))
AttributeError: 'StaticText' object has no attribute 'SetLabelText'
```

Am I missing something? I just reinstalled a fresh version of Gooey from github (`pip install -U git+https://github.com/chriskiehl/Gooey.git`). It might be a bug.

edit : I'm running py27 on a Fedora 20.

Let me know if I can help!

Thx

**Comment by chriskiehl** [comment]
Couple of quirks have been smoothed out on the Linux side or things. I'm can successfully run Gooey under Ubuntu without issue. Do you want to pull a fresh copy and try it on your Mint system?
