### ISSUE TITLE
Exception when using parent parser

### ISSUE THREAD

**Issue by thorstenwagner** [chriskiehl/Gooey#462]
- [ ] OS KUbuntu
 - [ ] Python Version 3.6.8
 - [ ] Gooey Version 1.0.2

Hi!

First: Gooey is fantastic! Thanks for making it available.

However, if you try to use parent parsers gooey crashed with the following exception:

```
Traceback (most recent call last):
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/bin/janni_denoise.py", line 10, in <module>
    sys.exit(_main_())
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 83, in inner2
    return payload(*args, **kwargs)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/site-packages/janni/jmain.py", line 98, in _main_
    parent.parse_args()
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/site-packages/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/site-packages/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/site-packages/gooey/util/functional.py", line 40, in merge
    return reduce(lambda acc, val: acc.update(val) or acc, copies)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/twagner/Applications/miniconda3/envs/cryolo2/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object

```

Here is a minimal example to reproduce:
```
from gooey import Gooey
import argparse

@Gooey
def _main_():
    parent = argparse.ArgumentParser(description="My program")
    parent.add_argument("-g","--global",help="A global variable")
    subparsers = parent.add_subparsers(help="")
    parser_child_a = subparsers.add_parser("childa", help="childa help", parents=[parent],
                                         add_help=False)
    parser_child_a.add_argument("-a",help="a option")

    parser_child_b = subparsers.add_parser("childb", help="childb help", parents=[parent],
                                           add_help=False)
    parser_child_b.add_argument("-b", help="b option")

    parent.parse_args()
```

Any ideas?

Thanks!
Thorsten

**Comment by chriskiehl** [comment]
Is that the exact code sample that causes the error? I'm currently unable to reproduce.

**Comment by thorstenwagner** [comment]
It is. I will try it again an come back to you.

**Comment by thorstenwagner** [comment]
Hm, with the latest commits it works also on my side. Strange.

However, the result is still not what I would expect
![gooey](https://user-images.githubusercontent.com/1113977/64430858-73182480-d0b9-11e9-823a-09c98b3142e7.png)

Why do I get a required argument? If mean, the selection on the left should be enough. Why to have to make the selection again in a dropdown box?
