### ISSUE TITLE
Horizontal Alignment Flags are Ignored in Horizontal sliders

### ISSUE THREAD

**Issue by Modelmat** [chriskiehl/Gooey#548]
- **OS**: Windows 10 v1909
 - **Python Version**:   3.8.2
 - **Gooey Version:** 1.0.3
 - Expected Behavior: examples run
 - Actual Behavior: Crashes with
```py
PS C:\Users\Modelmat\GooeyExamples> python .\examples\example_progress_bar_1.py
Traceback (most recent call last):
  File ".\examples\example_progress_bar_1.py", line 23, in <module>
    sys.exit(main())
  File "C:\Program Files\Python38\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File ".\examples\example_progress_bar_1.py", line 14, in main
    _ = parser.parse_args(sys.argv[1:])
  File "C:\Program Files\Python38\lib\site-packages\gooey\python_bindings\gooey_parser.py", line 114, in parse_args
    return self.parser.parse_args(args, namespace)
  File "C:\Program Files\Python38\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 82, in run_gooey
    application.run(build_spec)
  File "C:\Program Files\Python38\lib\site-packages\gooey\gui\application.py", line 21, in run
    app = build_app(build_spec)
  File "C:\Program Files\Python38\lib\site-packages\gooey\gui\application.py", line 30, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "C:\Program Files\Python38\lib\site-packages\gooey\gui\containers\application.py", line 42, in __init__
    self.header = FrameHeader(self, buildSpec)
  File "C:\Program Files\Python38\lib\site-packages\gooey\gui\components\header.py", line 33, in __init__
    self.layoutComponent()
  File "C:\Program Files\Python38\lib\site-packages\gooey\gui\components\header.py", line 75, in layoutComponent
    sizer.Add(headings_sizer, 1,
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_HORIZONTAL)" failed at ..\..\src\common\sizer.cpp(2106) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers```

 - **Code Example** All of the https://github.com/chriskiehl/GooeyExamples

**Comment by KrzysiekJ** [comment]
Looks like the same issue as #549.

**Comment by chriskiehl** [comment]
Yeah, wxpython 4.1.0 silently introduced some changes. I cut a Gooey release yesterday to downgrade the wx version. See: https://github.com/chriskiehl/Gooey/releases
