### ISSUE TITLE
poll_external_updates=True not working

### ISSUE THREAD

**Issue by frederikvs** [chriskiehl/Gooey#584]
I wanted to use the `poll_external_updates` feature, but I can't get it to work. Simply adding that option go Gooey gives errors.

I also tried running the dynamic updates example, but it's giving me the same errors.
https://github.com/chriskiehl/GooeyExamples/blob/master/examples/dynamic_updates.py 

 -  MacOS Mojave 10.14.6 (18G3020)
 -  Python Version  3.6.4
 -  Gooey Version Gooey==1.0.3.1

The error I'm getting is : 

```
 python3 dynamic_updates.py 
Traceback (most recent call last):
  File "dynamic_updates.py", line 122, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File "dynamic_updates.py", line 55, in main
    args = parser.parse_args()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/python_bindings/gooey_parser.py", line 114, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 82, in run_gooey
    application.run(build_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/application.py", line 21, in run
    app = build_app(build_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/application.py", line 30, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 70, in __init__
    self.fetchExternalUpdates()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 160, in fetchExternalUpdates
    self.buildSpec['encoding']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gooey/gui/seeder.py", line 15, in fetchDynamicProperties
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3' -u 'dynamic_updates.py' gooey-seed-ui --ignore-gooey": "'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3' -u 'dynamic_updates.py' gooey-seed-ui --ignore-gooey"
```

**Comment by frederikvs** [comment]
Note : on a windows the example works just fine, so I'm guessing the experimental feature just doesn't work on MacOS?

**Comment by chriskiehl** [comment]
Resolved via https://github.com/chriskiehl/Gooey/commit/560ce41d27ac6dff52db2258deab7adcfc5c98ff
