### ISSUE TITLE
OSError: [Errno 63] File name too long

### ISSUE THREAD

**Issue by phirst** [chriskiehl/Gooey#605]
- OS: `Catalina 10.15.6`
- Python: `3.7.6` & `3.8.4` 
- Gooey: `1.0.4` & `1.0.3.1`
- wXPython: `4.0.7` (tried `4.1.0` with and Gooey forced the downgrade to `4.0.7`).
 
After upgrading to the latest macOS (Catalina 10.15.6) things when pear shaped.  Other than the Catalina upgrade, there were _no changes in my Python app_.  The GUI fires up, but after hitting `Start`, this is what happens:

```
Traceback (most recent call last):
  File "/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/lib/python3.7/site-packages/gooey/gui/processor.py", line 52, in run
    stderr=subprocess.STDOUT, shell=self.shell_execution, env=env)
  File "/Users/myUserName/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/myUserName/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 63] File name too long: b"'/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/bin/python3' -u 'deviceHealthReport.py' --ignore-gooey Manual --ServerURL 'https://somewebserver.com/' --PrivateAuthority 'https://' --UserCredentialsFile 'aFileName' --CompanyName 'PS Test' --ReportType 'All Active Devices' --fileIdType 'guid or userUid' --minArchiveSize '1000000' --rangeValuesGoodMin '90' --rangeValuesWarningMin '75' --daysSinceLastCompleted '5' --daysSinceLastConnected '5' --daysSinceLastBackupActivty '5' --daysBetweenConnectedAndCompleted '3' --minBackupPercent '0' --maxBackupPercent '100' --excludedColumns 'archiveGuid' 'orgUid' 'orgExtRef' 'userUid' 'destinationUid' 'destinationName' 'serverUid' 'serverName' 'status' 'userStatus' 'osVersion' 'address' 'remoteAddress' 'creationDate' 'coldStorage' 'mostRecentUserProfileCreationResult' 'mostRecentUserProfileBackupResult' --makePDF --createZipFile --unhealthyReport --includeUserReport --userReportField 'Reports for Each' --sortField 'lastConnectedDate' --sortDir 'DESC' --incChildOrgs --dateField 'lastConnectedDate' --legalHoldPrimarySort 'Most Recently Connected' --duplicateFields 'userUid' 'deviceUid' 'destinationUid' --daysConnectedBins '0,1,5,10,20,30,60,90,180,365,10000000' --dayConnectedBinLabels '1,2-5,6-10,11-20,21-30,31-60,61-90,91-180,181-365,>365' --includeLegalHoldUid --maxPageSize '1000' --defaultReportDir 'DeviceHealthReport' --defaultReportName 'DeviceHealthReport' --reportTypes 'CSV' --minClientVersion '7.0.0' --maxDeviceCount '4' --showLogging --logLevel 'INFO' --saveSettings"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/lib/python3.7/site-packages/wx/core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/lib/python3.7/site-packages/gooey/gui/containers/application.py", line 90, in onStart
    self.clientRunner.run(self.buildCliString())
  File "/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/lib/python3.7/site-packages/gooey/gui/processor.py", line 57, in run
    stderr = subprocess.STDOUT, shell = self.shell_execution, env=env)
  File "/Users/myUserName/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/myUserName/.pyenv/versions/3.7.6/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 63] File name too long: "'/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/bin/python3' -u 'deviceHealthReport.py' --ignore-gooey Manual --ServerURL 'https://somewebserver.com/' --PrivateAuthority 'https://' --UserCredentialsFile 'aFileName' --CompanyName 'PS Test' --ReportType 'All Active Devices' --fileIdType 'guid or userUid' --minArchiveSize '1000000' --rangeValuesGoodMin '90' --rangeValuesWarningMin '75' --daysSinceLastCompleted '5' --daysSinceLastConnected '5' --daysSinceLastBackupActivty '5' --daysBetweenConnectedAndCompleted '3' --minBackupPercent '0' --maxBackupPercent '100' --excludedColumns 'archiveGuid' 'orgUid' 'orgExtRef' 'userUid' 'destinationUid' 'destinationName' 'serverUid' 'serverName' 'status' 'userStatus' 'osVersion' 'address' 'remoteAddress' 'creationDate' 'coldStorage' 'mostRecentUserProfileCreationResult' 'mostRecentUserProfileBackupResult' --makePDF --createZipFile --unhealthyReport --includeUserReport --userReportField 'Reports for Each' --sortField 'lastConnectedDate' --sortDir 'DESC' --incChildOrgs --dateField 'lastConnectedDate' --legalHoldPrimarySort 'Most Recently Connected' --duplicateFields 'userUid' 'deviceUid' 'destinationUid' --daysConnectedBins '0,1,5,10,20,30,60,90,180,365,10000000' --dayConnectedBinLabels '1,2-5,6-10,11-20,21-30,31-60,61-90,91-180,181-365,>365' --includeLegalHoldUid --maxPageSize '1000' --defaultReportDir 'DeviceHealthReport' --defaultReportName 'DeviceHealthReport' --reportTypes 'CSV' --minClientVersion '7.0.0' --maxDeviceCount '4' --showLogging --logLevel 'INFO' --saveSettings"
```

Expected:  Script runs just fine.
Actual:  Error (see above).

Note I have other similar scripts with fewer arguments and they're doing the same thing.  I've tried various versions of Python (3.7.6 & 3.8.4), Gooey (1.0.3.1 & 1.0.4) and wxPython (when possible).

**Comment by chriskiehl** [comment]
Do you have a small reproducible example? 

Are you overriding the default shell behavior with `@Gooey(requires_shell=False)` by any chance? 

I do note that I can recreate this OS error via subprocess by passing in your string without `shell=True`

So, this gives an OSError
```
subprocess.Popen("'/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/bin/python3' -u 'deviceHealthReport.py' --ignore-gooey Manual --ServerURL 'https://somewebserver.com/' --PrivateAuthority 'https://' --UserCredentialsFile 'aFileName' --CompanyName 'PS Test' --ReportType 'All Active Devices' --fileIdType 'guid or userUid' --minArchiveSize '1000000' --rangeValuesGoodMin '90' --rangeValuesWarningMin '75' --daysSinceLastCompleted '5' --daysSinceLastConnected '5' --daysSinceLastBackupActivty '5' --daysBetweenConnectedAndCompleted '3' --minBackupPercent '0' --maxBackupPercent '100' --excludedColumns 'archiveGuid' 'orgUid' 'orgExtRef' 'userUid' 'destinationUid' 'destinationName' 'serverUid' 'serverName' 'status' 'userStatus' 'osVersion' 'address' 'remoteAddress' 'creationDate' 'coldStorage' 'mostRecentUserProfileCreationResult' 'mostRecentUserProfileBackupResult' --makePDF --createZipFile --unhealthyReport --includeUserReport --userReportField 'Reports for Each' --sortField 'lastConnectedDate' --sortDir 'DESC' --incChildOrgs --dateField 'lastConnectedDate' --legalHoldPrimarySort 'Most Recently Connected' --duplicateFields 'userUid' 'deviceUid' 'destinationUid' --daysConnectedBins '0,1,5,10,20,30,60,90,180,365,10000000' --dayConnectedBinLabels '1,2-5,6-10,11-20,21-30,31-60,61-90,91-180,181-365,>365' --includeLegalHoldUid --maxPageSize '1000' --defaultReportDir 'DeviceHealthReport' --defaultReportName 'DeviceHealthReport' --reportTypes 'CSV' --minClientVersion '7.0.0' --maxDeviceCount '4' --showLogging --logLevel 'INFO' --saveSettings")
```

Whereas having the appropriate shell value will succeed. 


```
subprocess.Popen("'/Users/myUserName/.pyenv/versions/3.7.6/envs/buildpy/bin/python3' -u 'deviceHealthReport.py' --ignore-gooey Manual --ServerURL 'https://somewebserver.com/' --PrivateAuthority 'https://' --UserCredentialsFile 'aFileName' --CompanyName 'PS Test' --ReportType 'All Active Devices' --fileIdType 'guid or userUid' --minArchiveSize '1000000' --rangeValuesGoodMin '90' --rangeValuesWarningMin '75' --daysSinceLastCompleted '5' --daysSinceLastConnected '5' --daysSinceLastBackupActivty '5' --daysBetweenConnectedAndCompleted '3' --minBackupPercent '0' --maxBackupPercent '100' --excludedColumns 'archiveGuid' 'orgUid' 'orgExtRef' 'userUid' 'destinationUid' 'destinationName' 'serverUid' 'serverName' 'status' 'userStatus' 'osVersion' 'address' 'remoteAddress' 'creationDate' 'coldStorage' 'mostRecentUserProfileCreationResult' 'mostRecentUserProfileBackupResult' --makePDF --createZipFile --unhealthyReport --includeUserReport --userReportField 'Reports for Each' --sortField 'lastConnectedDate' --sortDir 'DESC' --incChildOrgs --dateField 'lastConnectedDate' --legalHoldPrimarySort 'Most Recently Connected' --duplicateFields 'userUid' 'deviceUid' 'destinationUid' --daysConnectedBins '0,1,5,10,20,30,60,90,180,365,10000000' --dayConnectedBinLabels '1,2-5,6-10,11-20,21-30,31-60,61-90,91-180,181-365,>365' --includeLegalHoldUid --maxPageSize '1000' --defaultReportDir 'DeviceHealthReport' --defaultReportName 'DeviceHealthReport' --reportTypes 'CSV' --minClientVersion '7.0.0' --maxDeviceCount '4' --showLogging --logLevel 'INFO' --saveSettings", shell=True)
```

Baring that, I'd need an example to be able to recreate and debug

**Comment by phirst** [comment]
@chriskiehl 

I'm working on a small reproducible bit of code to send you.

One thing I noticed is that if I completely remove the `requires_shell` argument it starts working again.

~P
