### ISSUE TITLE
Bug: Index Error In formatters.py

### ISSUE THREAD

**Issue by Th3Tr1ckst3r** [chriskiehl/Gooey#629]
I was using this Python3.7. code to test the new updates, and discovered a new bug using the following code:

```Python
#Test App
import os
import sys
import argparse
from gooey import Gooey
from gooey import GooeyParser


def test(args):
	try:
		print(args.three)
		sys.exit(0)
	except KeyboardInterrupt:
		sys.exit(1)


@Gooey(program_name="Test")
def main():
	try:
		global parser
		parser = GooeyParser(description='Test')
		parser.add_argument('one', widget="CheckBox", action='store_true', help='Test 1')
		parser.add_argument('two', widget="CheckBox", action='store_true', help='Test 2')
		parser.add_argument('three',  help='Test 3')
		args = parser.parse_args()
		test(args)
	except KeyboardInterrupt:
		sys.exit(1)
		
		
if __name__ == "__main__":
	main()
	sys.exit(1)
```

I then got the following error here:

```Python
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\wx\core.py", line 3285, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\containers\application.py", line 87, in onStart
    if config.isValid():
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\components\config.py", line 50, in isValid
    states = [widget.getValue() for widget in self.reifiedWidgets]
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\components\config.py", line 50, in <listcomp>
    states = [widget.getValue() for widget in self.reifiedWidgets]
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\components\widgets\bases.py", line 134, in getValue
    'cmd': self.formatOutput(self._meta, value),
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\components\widgets\checkbox.py", line 50, in formatOutput
    return formatters.checkbox(metatdata, value)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\gooey\gui\formatters.py", line 9, in checkbox
    return metadata['commands'][0] if value else None
IndexError: list index out of range
```

I'd appreciate any feedback, I'm not sure wether this is due to the new updates, or not. Before I started testing this, I did use pip uninstall Gooey, and pip install Gooey to get the latest version.

Thank you.

**Comment by Th3Tr1ckst3r** [comment]
I discovered what was going on, but need to do more testing first. Closing this issue for now.

**Comment by changkuanshenhj** [comment]
how deal with this solution?I met the same bug.
