### ISSUE TITLE
Cannot install Gooey using pip.

### ISSUE THREAD

**Issue by TimotheeJeannin** [chriskiehl/Gooey#67]
When in try to install Gooey using pip ( `pip install https://github.com/chriskiehl/Gooey.git` ) I get this error:

    Traceback (most recent call last):
      File "/home/tim/Workspace/thedotabot/task_queue/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/home/tim/Workspace/thedotabot/task_queue/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/home/tim/Workspace/thedotabot/task_queue/env/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
        do_download,
      File "/home/tim/Workspace/thedotabot/task_queue/env/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
        self.session,
      File "/home/tim/Workspace/thedotabot/task_queue/env/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
        unpack_file(temp_location, location, content_type, link)
      File "/home/tim/Workspace/thedotabot/task_queue/env/local/lib/python2.7/site-packages/pip/util.py", line 627, in unpack_file
        and is_svn_page(file_contents(filename))):
      File "/home/tim/Workspace/thedotabot/task_queue/env/local/lib/python2.7/site-packages/pip/util.py", line 210, in file_contents
        return fp.read().decode('utf-8')
      File "/home/tim/Workspace/thedotabot/task_queue/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
        return codecs.utf_8_decode(input, errors, True)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

It also would be nice to publish this great project on PyPI. :)

**Comment by chriskiehl** [comment]
Now Uploaded! 

https://pypi.python.org/pypi?name=Gooey&version=0.1.1&:action=display

**Comment by TimotheeJeannin** [comment]
Great ! Thank you !
