### ISSUE TITLE
Fails in line stderr=subprocess.STDOUT, shell=self.shell_execution, env=env)

### ISSUE THREAD

**Issue by blackcatpro777** [chriskiehl/Gooey#671]
Hi,

My code fails in the below line in Windows 10, but the same python code works fine in macbook. I started facing this issue only after I tried converting the code to .exe using pyinstaller. I tried in python 3.9, 3.8 and finally 3.7 all throws the same error.

C:\Users\Blackcatpro777\PycharmProjects\NIFFA\venv\Scripts\python.exe C:/Users/Blackcatpro777/PycharmProjects/NIFFA/main.py
Traceback (most recent call last):
  File "C:\Users\Blackcatpro777\PycharmProjects\NIFFA\venv\lib\site-packages\gooey\gui\processor.py", line 51, in run
    stderr=subprocess.STDOUT, shell=self.shell_execution, env=env)
  File "C:\Users\Blackcatpro777\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Blackcatpro777\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Blackcatpro777\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'int' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Blackcatpro777\PycharmProjects\NIFFA\venv\lib\site-packages\wx\core.py", line 3383, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Users\Blackcatpro777\PycharmProjects\NIFFA\venv\lib\site-packages\gooey\gui\containers\application.py", line 92, in onStart
    self.clientRunner.run(self.buildCliString())
  File "C:\Users\Blackcatpro777\PycharmProjects\NIFFA\venv\lib\site-packages\gooey\gui\processor.py", line 56, in run
    stderr = subprocess.STDOUT, shell = self.shell_execution, env=env)
  File "C:\Users\Blackcatpro777\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Blackcatpro777\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

 - [ ] OS - Windows 10
 - [ ] Python Version - Python 3.7 (32 bit)
 - [ ] Gooey Version - 1.0.8
 - [ ] Thorough description of problem - - The gooey screen gets the input xlsx file path in first text box and I enter a search string in the next textbox and after clicking START, it should show the information or NOT FOUND message if that string not found in the excel
     - [ ] Expected Behavior - The string should be searched in excel after clicking START
     - [ ] Actual Behavior - It throws the above error after I click START

![image](https://user-images.githubusercontent.com/72376911/107871168-27b19a80-6e97-11eb-86e9-c3f5efa26e19.png)

**Comment by Lazloo** [comment]
Anything new here?

**Comment by blackcatpro777** [comment]
I resolved by shutting off the shell by passing False to the Gooey Decorator, now my code works fine.

@Gooey(requires_shell=False)
def main(): 
   ...rest of code
