### ISSUE TITLE
Gooey setuptools > 58 for _2to3 does not allow pip install

### ISSUE THREAD

**Issue by Gerryjj** [chriskiehl/Gooey#824]
I was referred to Gooey by bje at NEMO, which uses Gooey, who wrote...
Are you able to install Gooey using pip install Gooey? If that package doesn't install, you'll need to take that up with [chriskiehl/Gooey](https://github.com/chriskiehl/Gooey).

There is a reference to what appears to be the problem at Stackoverflow where it suggests using setuptools==58.
While that runs, i still get the error afterwards. 
I don't think i need _2to3, but i can't be sure.

PS C:\Users\Username> pip install gooey                                
Collecting gooey
  Using cached Gooey-1.0.8.1-py2.py3-none-any.whl (680 kB)
Requirement already satisfied: pygtrie>=2.3.3 in c:\users\username\venv\lib\site-packages (from gooey) (2.4.2)
Requirement already satisfied: Pillow>=4.3.0 in c:\users\username\venv\lib\site-packages (from gooey) (9.1.1)
Requirement already satisfied: colored>=1.3.93 in c:\users\username\venv\lib\site-packages (from gooey) (1.4.3)
Collecting psutil>=5.4.2
  Using cached psutil-5.9.1-cp310-cp310-win_amd64.whl (245 kB)
Collecting wxpython>=4.1.0
  Using cached wxPython-4.1.1.tar.gz (66.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in c:\users\username\venv\lib\site-packages (from wxpython>=4.1.0->gooey) (1.16.0)
Requirement already satisfied: numpy in c:\users\username\venv\lib\site-packages (from wxpython>=4.1.0->gooey) (1.23.0)
Building wheels for collected packages: wxpython
  Building wheel for wxpython (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      C:\Users\Username\venv\lib\site-packages\setuptools\dist.py:710: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'use_2to3'
        warnings.warn(msg)
      running bdist_wheel
      running build
      C:\Users\Username\AppData\Local\Temp\pip-install-evqy7rak\wxpython_573ae266518743aa96e3f7c564e10160\build.py:41: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.dep_util import newer, newer_group
      Will build using: "C:\Users\Username\venv\Scripts\python.exe"
      3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.1.1

      Running command: build
      Running command: build_wx
      Command '"C:\Users\Username\venv\Scripts\python.exe" -c "import setuptools, distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
      Traceback (most recent call last):

        File "<string>", line 1, in <module>

        File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\distutils\msvc9compiler.py", line 371, in initialize

          vc_env = query_vcvarsall(VERSION, plat_spec)

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall

          return EnvironmentInfo(arch, ver).return_env()

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 1740, in return_env

          [self.VCIncludes,

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes

          return [join(self.si.VCInstallDir, 'Include'),

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir

          raise distutils.errors.DistutilsPlatformError(msg)

      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      Finished command: build_wx (0.286s)
      Finished command: build (0.286s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\Users\Username\venv\Scripts\python.exe" -u build.py build
      Command '"C:\Users\Username\venv\Scripts\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxpython
  Running setup.py clean for wxpython
Failed to build wxpython
Installing collected packages: wxpython, psutil, gooey
  Running setup.py install for wxpython ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wxpython did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      C:\Users\Username\venv\lib\site-packages\setuptools\dist.py:710: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'use_2to3'
        warnings.warn(msg)
      running install
      running build
      C:\Users\Username\AppData\Local\Temp\pip-install-evqy7rak\wxpython_573ae266518743aa96e3f7c564e10160\build.py:41: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.dep_util import newer, newer_group
      Will build using: "C:\Users\Username\venv\Scripts\python.exe"
      3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
      Python's architecture is 64bit
      cfg.VERSION: 4.1.1

      Running command: build
      Running command: build_wx
      Command '"C:\Users\Username\venv\Scripts\python.exe" -c "import setuptools, distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
      Traceback (most recent call last):

        File "<string>", line 1, in <module>

        File "C:\Users\Username\AppData\Local\Programs\Python\Python310\lib\distutils\msvc9compiler.py", line 371, in initialize

          vc_env = query_vcvarsall(VERSION, plat_spec)

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall

          return EnvironmentInfo(arch, ver).return_env()

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 1740, in return_env

          [self.VCIncludes,

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes

          return [join(self.si.VCInstallDir, 'Include'),

        File "C:\Users\Username\venv\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir

          raise distutils.errors.DistutilsPlatformError(msg)

      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      Finished command: build_wx (0.262s)
      Finished command: build (0.262s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.

      "C:\Users\Username\venv\Scripts\python.exe" -u build.py build
      Command '"C:\Users\Username\venv\Scripts\python.exe" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxpython

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Gerryjj** [comment]
Is this a reason to eliminate a dependency on _2to3?
Should that need to be done in setuptools or in Gooey?

**Comment by Gerryjj** [comment]
I went back to setuptools==57.5. Still get the distutils issue referencing MS C++ version, but it is the latest.
![image](https://user-images.githubusercontent.com/8576108/180591609-14c1dcdb-4a02-4ddb-a02c-c19fa44772e5.png)
Is there some other way to build?

**Comment by Gerryjj** [comment]
This workaround seems to work albeit only with setuptools=57.5
first.
https://morioh.com/p/1c920e8e864e
It might be an idea to include a demo app for verification.
