### ISSUE TITLE
The GUI goes blank when switching tabs in  1.2.0-alpha

### ISSUE THREAD

**Issue by CKrawczyk** [chriskiehl/Gooey#826]
- OS: MacOS Monterey (Intell chip)
 - Python Version: 3.10 (from conda)
 - Gooey Version : 1.2.0-alpha (from the 1.2.1-release git branch)

My GUI has three tabs, when I click on a new tab the GUI goes blank and I see the error message:

```bash
Traceback (most recent call last):
  File ".../anaconda3/envs/aggregation/lib/python3.10/site-packages/gooey/gui/application/application.py", line 264, in handleSelectAction
    self.set_state(assoc(self.state, 'activeSelection', event.Selection))
  File ".../anaconda3/envs/aggregation/lib/python3.10/site-packages/rewx/core.py", line 212, in set_state
    patch(self.base, self.render())
  File ".../anaconda3/envs/aggregation/lib/python3.10/site-packages/rewx/core.py", line 99, in patch
    update(vdom, dom)
  File ".../anaconda3/envs/aggregation/lib/python3.10/site-packages/rewx/dispatch.py", line 26, in wrapper
    return registry[element['type']](element, parent)
  File ".../anaconda3/envs/aggregation/lib/python3.10/site-packages/rewx/widgets.py", line 103, in frame
    frame.taskbarIcon = wx.adv.TaskBarIcon(iconType=wx.adv.TBI_DOCK)
wx._core.wxAssertionError: C++ assertion "!sm_dockIcon" failed at /Users/runner/miniforge3/conda-bld/wxpython_1638375585161/work/ext/wxWidgets/src/osx/cocoa/taskbar.mm(232) in wxTaskBarIconDockImpl(): You should never have more than one dock icon!
```

When I click the third tab everything comes back.

After some testing, it looks like **every second tab click** results in the GUI going black rather than a specific tab that is the issue.

This is my Gooey call if it helps:
```python
gooey.Gooey(
    program_name="Aggregate",
    default_size=(1000, 1150),
    progress_regex=r"^[a-zA-Z:\s|]+ (\d+)% .+$",
    terminal_font_family="Consolas",
    navigation='TABBED',
    image_dir=os.path.join(current_folder, 'icons')
)
```

**Comment by abrichr** [comment]
It looks like this is a problem in https://github.com/chriskiehl/re-wx/blob/main/rewx/widgets.py#L103.

A workaround is to modify `rewx/widgets.py::frame()` from this:

```
frame.taskbarIcon = wx.adv.TaskBarIcon(iconType=wx.adv.TBI_DOCK)
```

To this:
```
try:
    frame.taskbarIcon = wx.adv.TaskBarIcon(iconType=wx.adv.TBI_DOCK)
except wx._core.wxAssertionError:
    pass 
```

This prevents the exception and updates the UI as expected.
