### ISSUE TITLE
can't install Gooyey example

### ISSUE THREAD

**Issue by elycheikhsmail** [chriskiehl/Gooey#834]
Hello There, Future Issue Creator! 

 

 - [ ]  ubuntu 20.04 latest version
 - [ ]Python 3.10.4
 - [ ] Gooey Version 
 - [ ]  can install example
     - [ ] Expected Behavior 
     - [ ] pip install -r requirements.txt  failed 
 
 - [ ] Screenshot
 ```
pip install -r requirements.txt 
Collecting RXPY>=0.1.0
  Using cached RXPY-0.1.0.zip (90 kB)
  Preparing metadata (setup.py) ... done
Collecting Pillow>=4.3.0
  Using cached Pillow-9.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.2 MB)
Collecting psutil>=5.4.2
  Using cached psutil-5.9.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Collecting Gooey>=1.0.1
  Using cached Gooey-1.0.8.1-py2.py3-none-any.whl (680 kB)
Collecting colored>=1.3.93
  Using cached colored-1.4.3.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Collecting wxpython>=4.1.0
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error

error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-psxhy_90/wxpython_a30012a11d304f53914f1b91d3cc52ff/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-psxhy_90/wxpython_a30012a11d304f53914f1b91d3cc52ff/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by caiostringari** [comment]
This is related to this issue:

https://github.com/wxWidgets/Phoenix/issues/2225

**Comment by elycheikhsmail** [comment]
Ok thank you

**Comment by abrichr** [comment]
To save others a click:

```
pip install attrdict
```
