### ISSUE TITLE
/usr/lib64/python2.7/site-packages/gooey/python_bindings/source_parser.py:78: AttributeError: 'str' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by d33tah** [chriskiehl/Gooey#84]
```
[23:22:41][~/workspace/internet-census-2012-research/nmap/servicematch]$ python explore-format.py 
Traceback (most recent call last):
  File "explore-format.py", line 187, in <module>
    main()
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 118, in inner
    parser = get_parser(main_module_path)
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 161, in get_parser
    return source_parser.extract_parser(module_path)
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/source_parser.py", line 132, in extract_parser
    funcs = get_nodes_by_instance_type(nodes, _ast.FunctionDef)
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/source_parser.py", line 71, in get_nodes_by_instance_type
    return [node for node in walk_tree(nodes) if isinstance(node, object_type)]
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/source_parser.py", line 82, in walk_tree
    for _ in walk_tree(val): yield _
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/source_parser.py", line 82, in walk_tree
    for _ in walk_tree(val): yield _
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/source_parser.py", line 82, in walk_tree
    for _ in walk_tree(val): yield _
  File "/usr/lib64/python2.7/site-packages/gooey/python_bindings/source_parser.py", line 78, in walk_tree
    d = node.__dict__
AttributeError: 'str' object has no attribute '__dict__'
```

Below is the code:

```python
#!/usr/bin/python

"""

explore-format.py

Usage:

python explore-format.py <input file> <output file>

Build a binary database of Internet Census 2012 service fingerprint data set.
"""

import socket
import struct
import sys
import zlib
from StringIO import StringIO
import md5
import argparse
from gooey import Gooey


PROBE_NAMES = [
    "TCP_afp",
    "TCP_ajp",
    "TCP_apple-iphoto",
    "TCP_Arucer",
    "TCP_couchbase-data",
    "TCP_crossdomainxml",
    "TCP_DistCCD",
    "TCP_DNSStatusRequest",
    "TCP_DNSVersionBindReq",
    "TCP_drda",
    "TCP_EMPTY_PROBE",
    "TCP_epmd",
    "TCP_firebird",
    "TCP_FourOhFourRequest",
    "TCP_GenericLines",
    "TCP_GetRequest",
    "TCP_Hello",
    "TCP_Help",
    "TCP_HELP4STOMP",
    "TCP_hp-pjl",
    "TCP_HTTPOptions",
    "TCP_ibm-db2",
    "TCP_ibm-db2-das",
    "TCP_ibm-mqseries",
    "TCP_informix",
    "TCP_JavaRMI",
    "TCP_Kerberos",
    "TCP_LANDesk-RC",
    "TCP_LDAPBindReq",
    "TCP_LPDString",
    "TCP_Memcache",
    "TCP_memcached",
    "TCP_metasploit-xmlrpc",
    "TCP_mongodb",
    "TCP_ms-sql-s",
    "TCP_NCP",
    "TCP_NotesRPC",
    "TCP_OfficeScan",
    "TCP_oracle-tns",
    "TCP_pervasive-btrieve",
    "TCP_pervasive-relational",
    "TCP_Radmin",
    "TCP_redis-server",
    "TCP_riak-pbc",
    "TCP_RPCCheck",
    "TCP_RTSPRequest",
    "TCP_SIPOptions",
    "TCP_SMBProgNeg",
    "TCP_Socks4",
    "TCP_Socks5",
    "TCP_SqueezeCenter_CLI",
    "TCP_SSLSessionReq",
    "TCP_SSLv23SessionReq",
    "TCP_tarantool",
    "TCP_TerminalServer",
    "TCP_Verifier",
    "TCP_VerifierAdvanced",
    "TCP_vmware-esx",
    "TCP_vp3",
    "TCP_WMSRequest",
    "TCP_X11Probe",
    "TCP_ZendJavaBridge",
    "UDP_AFSVersionRequest",
    "UDP_Citrix",
    "UDP_DNS-SD",
    "UDP_DNSStatusRequest",
    "UDP_DNSVersionBindReq",
    "UDP_Help",
    "UDP_ibm-db2-das-udp",
    "UDP_Kerberos",
    "UDP_memcached",
    "UDP_NBTStat",
    "UDP_NTPRequest",
    "UDP_pc-anywhere",
    "UDP_pc-duo",
    "UDP_pc-duo-gw",
    "UDP_RPCCheck",
    "UDP_serialnumberd",
    "UDP_SIPOptions",
    "UDP_SNMPv1public",
    "UDP_SNMPv3GetRequest",
    "UDP_Sqlping",
    "UDP_SqueezeCenter",
    "UDP_sybaseanywhere",
    "UDP_vuze-dht",
    "UDP_xdmcp",
]


def decode_fp(fp):
    global known_chars
    ret = ""
    f = StringIO(fp)
    try:
        while True:
            b = f.read(1)
            if b == '':
                break
            if b != '=':
                ret += b
            else:
                ret += chr(int(f.read(2), 16))
    except ValueError:
        pass
    return ret


def run_pdb_hook(*args, **kwargs):
    import pdb
    import traceback
    traceback.print_exception(*args, **kwargs)
    pdb.pm()


def main(infile, outfile, port_no, probe_name):
    probe_dir = "%s-%s" % (port_no, probe_name)
    outfile = open(outfile, "w")
    onebyte_file = open("%s/1" % probe_dir, "w")
    port_no_bin = struct.pack(">h", port_no)
    probe_byte = chr(PROBE_NAMES.index(probe_name))
    #for line in sys.stdin:
    for line in open(infile):
        ip, timestamp, status, fp = line.split("\t")
        ip = socket.inet_aton(ip)
        timestamp = struct.pack(">I", int(timestamp))
        status = chr(int(status))
        if fp:
            fp = decode_fp(fp)
            #fp = zlib.compress(fp, 9)
        fp_len = len(fp)
        if fp_len > 1:
            fp_md5 = md5.md5(fp).digest()
            out = "%s%s%s%s%s%s" % (ip, port_no_bin, probe_byte, timestamp,
                                    status, fp_md5)
            outfile.write(out)
            outfile.flush()
            f = open("%s/%d" % (probe_dir, len(fp)), "a")
            f.write("%s%s%s" % (fp_md5, probe_byte, fp))
            f.close()
        elif fp_len == 1:
            out = "%s%s%s%s" % (ip, timestamp, status, fp)
            onebyte_file.write(out)
            onebyte_file.flush()
        else:
            pass  # no fingerprint, do nothing for now

@Gooey
def main2():
    parser = argparse.ArgumentParser()
    parser.add_argument('--infile', required=True)
    parser.add_argument('--outfile', required=True)
    parser.add_argument('--dirname', required=True)
    args = parser.parse_args()

    dirname_split = args.dirname.split('-')
    port_no = int(dirname_split[0])
    probe_name = '-'.join(dirname_split[1:])

    sys.excepthook = run_pdb_hook
    main(args.infile, args.outfile, port_no, probe_name)

if __name__ == "__main__":
  main2()
```

**Comment by d33tah** [comment]
Actually, there are two main() declarations by mistake. Rename the latter to `main2` and the error still won't go away.

**Comment by chriskiehl** [comment]
Fixed! Pull the latest version from github (not pip!) and you should be all set. The code that extracts the `argparse` stuff is a bit clunky, so feel free to re-open if anything is still wonky.
