### ISSUE TITLE
Dynamic Values broken on 1.2.1-release with Python 3.9.14, MacOS 12.0.1

### ISSUE THREAD

**Issue by abrichr** [chriskiehl/Gooey#845]
- [x] OS: MacOS 12.0.1
 - [x] Python Version: Python 3.9.14
 - [x] Gooey Version: `1.2.1-release` (git branch) / `1.2.0-ALPHA` (`gooey.__version__`)
 - [x] Thorough description of problem :

Steps to reproduce:
1. run `python minimum_working_example.py`
2. click "start"
3. observe exception:
```
Traceback (most recent call last):
...
...lib/python3.9/site-packages/gooey/gui/util/time.py", line 38, in start
    self.wxTimer.Start()
wx._core.wxAssertionError: C++ assertion ""m_milli > 0"" failed at /Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/osx/core/timer.cpp(69) in Start(): invalid value for timer timeout
```
 - [x] Expected Behavior: at least one of `on_success()` or `on_error()` are called
 - [x] Actual Behavior: neither is called
 - [x] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 

`minimum_working_example.py`:
```
from typing import Mapping, Any, Optional

from gooey import Gooey, GooeyParser, Events, types


# monkeypatch; see
# https://github.com/chriskiehl/Gooey/issues/826#issuecomment-1240180894
def do_monkeypatch():
    from rewx import widgets
    from rewx.widgets import set_basic_props
    from rewx.dispatch import update
    import wx
    import sys

    @update.register(wx.Frame)
    def frame(element, instance: wx.Frame):
        props = element['props']
        set_basic_props(instance, props)
        if 'title' in props:
            instance.SetTitle(props['title'])
        if 'show' in props:
            instance.Show(props['show'])
        if 'icon_uri' in props:
            icon = wx.Icon(props['icon_uri'])
            instance.SetIcon(icon)
            if sys.platform != 'win32':
                # OSX needs to have its taskbar icon explicitly set
                # bizarrely, wx requires the TaskBarIcon to be attached to the Frame
                # as instance data (self.). Otherwise, it will not render correctly.
                try:
                    frame.taskbarIcon = wx.adv.TaskBarIcon(iconType=wx.adv.TBI_DOCK)
                except wx._core.wxAssertionError:
                    pass
                frame.taskbarIcon.SetIcon(icon)
        else:
            instance.SetIcon(wx.Icon(os.path.join(dirname, 'icon.png')))
        if 'on_close' in props:
            instance.Bind(wx.EVT_CLOSE, props['on_close'])
        return instance
    widgets.frame = frame
do_monkeypatch()


def on_success(args: Mapping[str, Any], state: types.PublicGooeyState) -> Optional[types.PublicGooeyState]:
    """
    You can do anything you want in the handler including 
    returning an updated UI state for your next run!   
    """ 
    logger.info(f"{args=} {state=}")
    return state

    
def on_error(args: Mapping[str, Any], state: types.PublicGooeyState) -> Optional[types.PublicGooeyState]:
    """
    You can do anything you want in the handler including 
    returning an updated UI state for your next run!   
    """ 
    logger.info(f"{args=} {state=}")
    return state    


@Gooey()
def main():
    parser = GooeyParser(
        on_success=on_success,
        on_error=on_error,
    )
    subs = parser.add_subparsers()

    arg_groups = [
        {
            "name": "arg_group_name",
            "args": [
                {
                    "name": "arg_name",
                },
            ],
        },
    ]

    for arg_group in arg_groups:
        group_name = arg_group["name"]
        group_args = arg_group["args"]
        subparser = subs.add_parser(group_name)
        subgroup = subparser.add_argument_group(
            group_name,
            gooey_options={
                "columns": 1,
            }
        )

        for arg_kwargs in group_args:
            arg_name = arg_kwargs.pop("name")
            subgroup.add_argument(arg_name, **arg_kwargs)

    parser.parse_args()


if __name__ == "__main__":
    main()
```

 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^

**Comment by abrichr** [comment]
On Python 3.9.13, Windows 10, the same example does not raise an exception (and does not require the monkeypatch), but the callbacks are still not called.

**Comment by abrichr** [comment]
The `FileNotFoundError` can be fixed by adding the following to `do_monkeypatch()` (from https://github.com/chriskiehl/Gooey/issues/813#issuecomment-1113911923):

```
    import subprocess
    from subprocess import CalledProcessError
    from json import JSONDecodeError

    from gooey.gui import seeder
    from gooey.python_bindings.types import Try, Success, Failure


    # https://github.com/chriskiehl/Gooey/issues/813#issuecomment-1113911923
    def communicate(cmd, encoding) -> Try:
        """
        Invoke the processes specified by `cmd`.
        Assumes that the process speaks JSON over stdout. Non-json response
        are treated as an error.

        Implementation Note: I don't know why, but `Popen` is like ~5-6x faster
        than `check_output`. in practice, it means waiting for ~1/10th
        of a second rather than ~7/10ths of a second. A
        difference which is pretty weighty when there's a
        user waiting on the other end.
        """

        cmd = cmd.replace("'", "").split()
        try:
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            out, err = proc.communicate()
            if out and proc.poll() == 0:
                return Success(deserialize_inbound(out, encoding))
            else:
                return Failure(CalledProcessError(proc.returncode, cmd, output=out, stderr=err))
        except JSONDecodeError as e:
            return Failure(e)
    seeder.communicate = communicate
```

Unfortunately the wxAssertionError remains, and the callbacks are still not called.

**Comment by abrichr** [comment]
It looks like the success handler is called if a value for "foo" is supplied on both Mac and Windows, but this is only apparent if the function raises an exception, i.e. printing has no effect:

```
def on_success(args: Mapping[str, Any], state: types.PublicGooeyState) -> Optional[types.PublicGooeyState]:
    """
    You can do anything you want in the handler including 
    returning an updated UI state for your next run!   
    """ 
    print(f"{args=} {state=}")
    success
    return state
```

```
Command '"C:\...\Python\Python39\python.exe" -u "ui_min.py" --gooey-state eyJhY3RpdmVfZm9ybSI6IFt7ImlkIjogImZvbyIsICJ0eXBlIjogIlRleHRGaWVsZCIsICJ2YWx1ZSI6ICJhc2RmIiwgInBsYWNlaG9sZGVyIjogIiIsICJlcnJvciI6ICIiLCAiZW5hYmxlZCI6IHRydWUsICJ2aXNpYmxlIjogdHJ1ZX1dfQ== --gooey-run-is-success -- "asdf"' returned non-zero exit status 1.b'args=Namespace(foo=\'asdf\') state={\'active_form\': [{\'id\': \'foo\', \'type\': \'TextField\', \'value\': \'asdf\', \'placeholder\': \'\', \'error\': \'\', \'enabled\': True, \'visible\': True}]}\r\n  File "C:\\Users\\qzhr1149\\Documents\\EMR Automation\\app\\ui_min.py", line 77, in <module>\r\n    main()\r\n  File "C:\\...\\Python\\Python39\\lib\\site-packages\\gooey\\python_bindings\\gooey_decorator.py", line 30, in inner\r\n    return f(*args, **kwargs)\r\n  File "C:\\Users\\qzhr1149\\Documents\\EMR Automation\\app\\ui_min.py", line 73, in main\r\n    parser.parse_args()\r\n  File "C:\\...\\Python\\Python39\\lib\\site-packages\\gooey\\python_bindings\\gooey_parser.py", line 177, in parse_args\r\n    return self.parser.parse_args(args, namespace)\r\n  File "C:\\...\\Python\\Python39\\lib\\site-packages\\gooey\\python_bindings\\control.py", line 165, in parse_args\r\n    write(\'\'.join(traceback.format_stack()))\r\n\r\nname \'success\' is not defined\r\n'b''
+=======================+
|Gooey Unexpected Error!|
+=======================+

Gooey encountered an unexpected error while trying to communicate 
with your program to process one of the ('VALIDATE_FORM', 'ON_SUCCESS', 'ON_ERROR') events.

These features are new and experimental! You may have encountered a bug! 

You can open a ticket with a small reproducible example here
https://github.com/chriskiehl/Gooey/issues
```

**Comment by abrichr** [comment]
Interacting with the file system in the callbacks appears to produce a race condition:

```
def dump_state(name, args, state):
    import json 
    import time
    with open(f"{name}-{time.time()}.json", "w") as f:
        json.dump({"args": args, "state": state}, f)


def on_success(args: Mapping[str, Any], state: types.PublicGooeyState) -> Optional[types.PublicGooeyState]:
    """
    You can do anything you want in the handler including 
    returning an updated UI state for your next run!   
    """ 
    dump_state("success", args, state)
    return state

    
def on_error(args: Mapping[str, Any], state: types.PublicGooeyState) -> Optional[types.PublicGooeyState]:
    """
    You can do anything you want in the handler including 
    returning an updated UI state for your next run!   
    """ 
    dump_state("failure", args, state)
    return state    
```

```
cat success-1662652539.935036.json
{"args": %
```

The resulting file is truncated. No file is produced if the variable is left empty, i.e. failure callback is not called.

**Comment by abrichr** [comment]
It appears that the callbacks are being called, just not printing to stdout. The following works on both platforms:

```
from typing import Mapping, Any, Optional

from gooey import Gooey, GooeyParser, Events, types


# monkeypatch; see
# https://github.com/chriskiehl/Gooey/issues/826#issuecomment-1240180894
def do_monkeypatch():
    from rewx import widgets
    from rewx.widgets import set_basic_props
    from rewx.dispatch import update
    import wx
    import sys

    @update.register(wx.Frame)
    def frame(element, instance: wx.Frame):
        props = element['props']
        set_basic_props(instance, props)
        if 'title' in props:
            instance.SetTitle(props['title'])
        if 'show' in props:
            instance.Show(props['show'])
        if 'icon_uri' in props:
            icon = wx.Icon(props['icon_uri'])
            instance.SetIcon(icon)
            if sys.platform != 'win32':
                # OSX needs to have its taskbar icon explicitly set
                # bizarrely, wx requires the TaskBarIcon to be attached to the Frame
                # as instance data (self.). Otherwise, it will not render correctly.
                try:
                    frame.taskbarIcon = wx.adv.TaskBarIcon(iconType=wx.adv.TBI_DOCK)
                except wx._core.wxAssertionError:
                    pass
                frame.taskbarIcon.SetIcon(icon)
        else:
            instance.SetIcon(wx.Icon(os.path.join(dirname, 'icon.png')))
        if 'on_close' in props:
            instance.Bind(wx.EVT_CLOSE, props['on_close'])
        return instance
    widgets.frame = frame


    import subprocess
    from subprocess import CalledProcessError
    from json import JSONDecodeError

    from gooey.gui import seeder
    from gooey.python_bindings.types import Try, Success, Failure
    from gooey.python_bindings.coms import deserialize_inbound


    # https://github.com/chriskiehl/Gooey/issues/813#issuecomment-1113911923
    def communicate(cmd, encoding) -> Try:
        """
        Invoke the processes specified by `cmd`.
        Assumes that the process speaks JSON over stdout. Non-json response
        are treated as an error.

        Implementation Note: I don't know why, but `Popen` is like ~5-6x faster
        than `check_output`. in practice, it means waiting for ~1/10th
        of a second rather than ~7/10ths of a second. A
        difference which is pretty weighty when there's a
        user waiting on the other end.
        """

        cmd = cmd.replace("'", "").split()
        try:
            proc = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            out, err = proc.communicate()
            if out and proc.poll() == 0:
                return Success(deserialize_inbound(out, encoding))
            else:
                return Failure(CalledProcessError(proc.returncode, cmd, output=out, stderr=err))
        except JSONDecodeError as e:
            return Failure(e)
    if sys.platform != 'win32':
        seeder.communicate = communicate

do_monkeypatch()


def dump_state(name, args, state):
    import pickle
    with open(f"{name}.pkl", "wb") as f:
        pickle.dump({"args": args, "state": state}, f)


def on_success(args: Mapping[str, Any], state: types.PublicGooeyState) -> Optional[types.PublicGooeyState]:
    """
    You can do anything you want in the handler including 
    returning an updated UI state for your next run!   
    """ 
    dump_state("success", args, state)
    """
    {'args': Namespace(foo='asdf'),
     'state': {'active_form': [{'enabled': True,
                                'error': '',
                                'id': 'foo',
                                'placeholder': '',
                                'type': 'TextField',
                                'value': 'asdf',
                                'visible': True}]}}
    """
    state["active_form"][0]["value"] = "updated"
    return state

    
def on_error(args: Mapping[str, Any], state: types.PublicGooeyState) -> Optional[types.PublicGooeyState]:
    """
    You can do anything you want in the handler including 
    returning an updated UI state for your next run!   
    """ 
    dump_state("failure", args, state)
    return state    


@Gooey(
    use_events=[
        Events.ON_SUCCESS,
        Events.ON_ERROR,
        Events.VALIDATE_FORM,
    ],
)
def main():
    parser = GooeyParser(
        on_success=on_success,
        on_error=on_error,
    )
    parser.add_argument("foo")
    parser.parse_args()

    # comment out for on_success; otherwise on_failure is called
    raise Exception("this is an exception")


if __name__ == "__main__":
    main()
```

To summarize:

- `on_success()` is called if no Exception is raised after the call to `parser.parse_args()`, otherwise `on_failure()` is called
- no additional Exceptions are raised on Windows
- the following additional Exception is raised on MacOS when a parameter value is supplied and the start button is pressed, regardless of success or failure: `wx._core.wxAssertionError: C++ assertion ""m_milli > 0"" failed at /Users/robind/projects/bb2/dist-osx-py39/build/ext/wxWidgets/src/osx/core/timer.cpp(69) in Start(): invalid value for timer timeout`
- the state is successfully modified in both `on_success` and `on_failure`
- if `Events.VALIDATE_FORM` is not included in the `use_events` parameter to `Gooey()`, the following is printed in the UI on both platforms:
```
usage: minimum_working_example.py [-h] [--ignore-gooey] foo
ui_min.py: error: the following arguments are required: foo
Command '['/.../bin/python', '-u', 'minimum_working_example.py', '--gooey-state', 'eyJhY3RpdmVfZm9ybSI6IFt7ImlkIjogImZvbyIsICJ0eXBlIjogIlRleHRGaWVsZCIsICJ2YWx1ZSI6ICIiLCAicGxhY2Vob2xkZXIiOiAiIiwgImVycm9yIjogIiIsICJlbmFibGVkIjogdHJ1ZSwgInZpc2libGUiOiB0cnVlfV19', '--gooey-run-is-failure']' returned non-zero exit status 2.b''b'usage: minimum_working_example.py [-h] [--gooey-state GOOEY_STATE] [--gooey-run-is-success]\n                 [--gooey-run-is-failure]\n                 foo\minimum_working_example.py: error: the following arguments are required: foo\n'
+=======================+
|Gooey Unexpected Error!|
+=======================+

Gooey encountered an unexpected error while trying to communicate 
with your program to process one of the ('VALIDATE_FORM', 'ON_SUCCESS', 'ON_ERROR') events.

These features are new and experimental! You may have encountered a bug! 

You can open a ticket with a small reproducible example here
https://github.com/chriskiehl/Gooey/issues
```
