### ISSUE TITLE
MultiDirChooser does not show paths in textbox after selecting folders

### ISSUE THREAD

**Issue by nicholasjaeger** [chriskiehl/Gooey#854]
Hello There, Future Issue Creator! 

>README: Are you suddenly seeing errors related to Alignment flags when starting Gooey? Upgrade your gooey installation to the latest version (`pip install -U gooey`) to resolve the errors! See [this issue](https://github.com/chriskiehl/Gooey/issues/549) for additional information. 

Found a bug? Just a friendly heads up, _debugging it requires information from you!_ Make sure the template below is filled out in its entirety. 

 - [ ] OS
 - [ ] Python Version 
 - [ ] Gooey Version 
 - [ ] Thorough description of problem 
     - [ ] Expected Behavior 
     - [ ] Actual Behavior 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [ ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^ 

Windows 10 Enterprise 21H2
Python 3.10.5
Gooey 1.0.8.1

`
first_parser = sub_parsers.add_parser('Convert')

first_parser.add_argument('folders', widget='MultiDirChooser',nargs='*')

When I run this code (this is a snippet) I am able to pull up the GUI and browse under the MultiDirChooser widget. When I select multiple folders (using CTRL) and select OK, there is nothing in the corresponding textfield and I get this error message in console immediately after pressing OK:

PS C:\Users\nicholas.jaeger> & "C:/Program Files/Python310/python.exe" c:/Users/nicholas.jaeger/Documents/GitHub/PDF-Docx-App/gui.py
Traceback (most recent call last):
  File "C:\Users\nicholas.jaeger\AppData\Roaming\Python\Python310\site-packages\gooey\gui\components\widgets\core\chooser.py", line 62, in spawnDialog
    self.processResult(self.getResult(fd))
  File "C:\Users\nicholas.jaeger\AppData\Roaming\Python\Python310\site-packages\gooey\gui\components\widgets\core\chooser.py", line 147, in getResult
    paths[i] = os.sep.join([drives.group('drive')] + parts[1:])
AttributeError: 'NoneType' object has no attribute 'group'

If I type in a value into the textbox and press OK, I have no issues, so I think there might be a missing argument or bug.

I think that this is because of there not being text in the textfield, 
`

**Comment by nicholaslivingstone** [comment]
```
My environment: 
 Windows 10 IoT Enterprise LTSC (Ver 21H2)
 Python 3.9.15
 Gooey 1.0.8.1
```
I've just encountered this issue as well. At least for me, it appears to be a bug with the `getResult()` method of `MultiDirChooser` and how it tries to remove volume labels from windows paths. **I encountered this bug when attempting to select a network mapped drive, the bug was not present when selecting a local folder path.** 

@nicholasjaeger What was the directory path you were trying to access? Was it also a network/non-local path? 

# Bug
Relevant code from [chooser.py](https://github.com/chriskiehl/Gooey/blob/be4b11b8f27f500e7326711641755ad44576d408/gooey/gui/components/widgets/core/chooser.py)
```
def getResult(self, dialog):
        paths = dialog.GetPaths()
        # Remove volume labels from Windows paths
        if 'nt' == os.name:
            for i, path in enumerate(paths):
                if path:
                    parts = path.split(os.sep)
                    vol = parts[0]
                    drives = re.match(r'.*\((?P<drive>\w:)\)', vol)
                    paths[i] = os.sep.join([drives.group('drive')] + parts[1:])

        return os.pathsep.join(paths)
```

### Expected behavior
If I select a local folder, like `C:\Intel`, `dialog.GetPaths()` will return 
`"Local Disk (C:)\\Intel"`


```
parts: ['Local Disk (C:)',  'Intel']
vol: 'Local Disk (C:)'
drives: <re.Match object; span=(0, 15), match='Local Disk (C:)'>
```
This works fine, as the match object contains the drive we're looking for. 

### Bug behavior
But if I select a folder on my mapped drive, like `Z:\MyFolder` located at `10.1.2.3`, `dialog.GetPaths()` will return 
`"CoolDriveName (\\10.1.2.3) (Z:)\\MyFolder"`

And we get the following variable values:
```
parts: ['CoolDriveName (',  '10.1.2.3) (Z:)',  'MyFolder']
vol: 'CoolDriveName ('
drives: None
```

It seems the core issue lies with the logic of `path.split(os.sep)` and the regex expression `.*\((?P<drive>\w:)\)`. It searches vol for the drive letter but can't find it since `path.split` unexpectedly splits the path. 

## Potential Solution
Since we can assume some constrains about windows paths, and we're only modifying the path for windows paths. I propose changing the logic to exclude path.split, and exclusively use a regex expression to format the path, like:
`.*\((?P<drive>\w:)\)\\(?P<path>.*)`

With new logic:

```
def getResult(self, dialog):
    paths = dialog.GetPaths()
    # Remove volume labels from Windows paths
    if 'nt' == os.name:
        for i, path in enumerate(paths):
            if path:
                path_components = re.match(r'.*\((?P<drive>\w:)\)\\(?P<path>.*)', path)
                drive = path_components.group('drive')
                path_parts = path_components.group('path')
                paths[i] = os.sep.join([drive, path_parts])

    return os.pathsep.join(paths)
```
It seems to resolve my issue. However, I think further testing should be done with this approach as it's a bit more reckless with escape characters and such.

**Comment by narbhar** [comment]
> ```
> My environment: 
>  Windows 10 IoT Enterprise LTSC (Ver 21H2)
>  Python 3.9.15
>  Gooey 1.0.8.1
> ```
> 
> I've just encountered this issue as well. At least for me, it appears to be a bug with the `getResult()` method of `MultiDirChooser` and how it tries to remove volume labels from windows paths. **I encountered this bug when attempting to select a network mapped drive, the bug was not present when selecting a local folder path.**
> 
> @nicholasjaeger What was the directory path you were trying to access? Was it also a network/non-local path?
> 
> # Bug
> Relevant code from [chooser.py](https://github.com/chriskiehl/Gooey/blob/be4b11b8f27f500e7326711641755ad44576d408/gooey/gui/components/widgets/core/chooser.py)
> 
> ```
> def getResult(self, dialog):
>         paths = dialog.GetPaths()
>         # Remove volume labels from Windows paths
>         if 'nt' == os.name:
>             for i, path in enumerate(paths):
>                 if path:
>                     parts = path.split(os.sep)
>                     vol = parts[0]
>                     drives = re.match(r'.*\((?P<drive>\w:)\)', vol)
>                     paths[i] = os.sep.join([drives.group('drive')] + parts[1:])
> 
>         return os.pathsep.join(paths)
> ```
> 
> ### Expected behavior
> If I select a local folder, like `C:\Intel`, `dialog.GetPaths()` will return `"Local Disk (C:)\\Intel"`
> 
> ```
> parts: ['Local Disk (C:)',  'Intel']
> vol: 'Local Disk (C:)'
> drives: <re.Match object; span=(0, 15), match='Local Disk (C:)'>
> ```
> 
> This works fine, as the match object contains the drive we're looking for.
> 
> ### Bug behavior
> But if I select a folder on my mapped drive, like `Z:\MyFolder` located at `10.1.2.3`, `dialog.GetPaths()` will return `"CoolDriveName (\\10.1.2.3) (Z:)\\MyFolder"`
> 
> And we get the following variable values:
> 
> ```
> parts: ['CoolDriveName (',  '10.1.2.3) (Z:)',  'MyFolder']
> vol: 'CoolDriveName ('
> drives: None
> ```
> 
> It seems the core issue lies with the logic of `path.split(os.sep)` and the regex expression `.*\((?P<drive>\w:)\)`. It searches vol for the drive letter but can't find it since `path.split` unexpectedly splits the path.
> 
> ## Potential Solution
> Since we can assume some constrains about windows paths, and we're only modifying the path for windows paths. I propose changing the logic to exclude path.split, and exclusively use a regex expression to format the path, like: `.*\((?P<drive>\w:)\)\\(?P<path>.*)`
> 
> With new logic:
> 
> ```
> def getResult(self, dialog):
>     paths = dialog.GetPaths()
>     # Remove volume labels from Windows paths
>     if 'nt' == os.name:
>         for i, path in enumerate(paths):
>             if path:
>                 path_components = re.match(r'.*\((?P<drive>\w:)\)\\(?P<path>.*)', path)
>                 drive = path_components.group('drive')
>                 path_parts = path_components.group('path')
>                 paths[i] = os.sep.join([drive, path_parts])
> 
>     return os.pathsep.join(paths)
> ```
> 
> It seems to resolve my issue. However, I think further testing should be done with this approach as it's a bit more reckless with escape characters and such.

In my case the windows paths are being parsed without the parenthesis at `dialog.GetPaths()` in the chooser.py file and thus this `r'.*\((?P<drive>\w:)\)' ` regex expression is giving the error. I removed the literal parenthesis parsing in this regex and made it `r'.*(?P<drive>\w:)'` and it seems to solve my issue.
I'm running Windows 10 2H2 19045.4780 build with Python 3.10.9 with Gooey 1.0.8.1 and wxpython 4.2.2

**Comment by abn6** [comment]
I am having the same issue (Windows 11, gooey 1.0.8.1)

I suggest this change:
```python
def getResult(self, dialog):
    paths = dialog.GetPaths()
    # Remove volume labels from Windows paths
    if 'nt' == os.name:
        for i, path in enumerate(paths):
            if path:
                parts = path.split(os.sep)
                vol = parts[0]
                drives = re.match(r'.*\((?P<drive>\w:)\)', vol)
                drives = re.match(r'.*(?P<drive>\w:)', vol) if drives is None else drives
                if drives is None:
                    continue
                paths[i] = os.sep.join([drives.group('drive')] + parts[1:])

    return os.pathsep.join(paths)
```

Then it is possible to use the `append` action as:
```python

def normalize_path(path: str) -> str:
    """Normalize path, handling Windows drive label quirks from file dialogs."""
    # Handle localized drive labels: "Disco local (C:)" (Spanish), "Local Disk (C:)" (English), etc.
    path = re.sub(r'(?:Disco local|Local Disk|Local Drive)\s*\(([A-Z]:)\)', r'\1', path, flags=re.IGNORECASE)
    return os.path.normpath(path.strip())

def get_additionals(additionals: list | str | None) -> list[str]:
    """Parse paths from MultiDirChooser or CLI with action='append' and nargs='*'."""
    if not additionals:
        return []

    if isinstance(additionals, list):
        result = []
        for item in additionals:
            if isinstance(item, list):
                # Flatten the nested list
                result.extend([normalize_path(p) for p in item if p and str(p).strip()])
            elif item and str(item).strip():
                result.append(normalize_path(item))
        return result

    if isinstance(additionals, str):
        return [normalize_path(additionals)] if additionals.strip() else []
    return []

parser = GooeyParser()
parser.add_argument(
    '-i',
    '--include',
    dest='includes',
    action='append',
    nargs='*',
    help='List of includes. In CLI you can repeat -i for each include',
    widget='MultiDirChooser'
)
args = parser.parse_args()
includes = get_additionals(args.includes)
```

This allows using `MultiDirChooser` in gooey and using the CLI as:
```bash
python main.py --ignore-gooey -i path1 -i path2
```

> [!NOTE]
> Using `default=[]` will result in the string `'[]'` (which appears in the GUI), not an actual list.
