### ISSUE TITLE
Exception when all arguments are optional

### ISSUE THREAD

**Issue by amorde** [chriskiehl/Gooey#87]
```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/gooey/gui/windows/footer.py", line 152, in OnStartButton
    self._controller.OnStartButton(event, self)
  File "/Library/Python/2.7/site-packages/gooey/gui/controller.py", line 48, in OnStartButton
    _required = self.core_gui.GetRequiredArgs()
  File "/Library/Python/2.7/site-packages/gooey/gui/windows/base_window.py", line 82, in GetRequiredArgs
    return self.config_panel.GetRequiredArgs()
  File "/Library/Python/2.7/site-packages/gooey/gui/windows/advanced_config.py", line 108, in GetRequiredArgs
    return [arg.GetValue() for arg in self.components.required_args]
TypeError: 'NoneType' object is not iterable
```

I have all optional arguments which have default values. If the user does not provide any of the arguments, they should be able to hit start and just use the defaults. I could probably whip up a one-line pull request to fix this but I want to make sure I understand it fully before doing so.

**Comment by chriskiehl** [comment]
Doh.. I'm an idiot. 

Sorry about that. Fixed!
