### ISSUE TITLE
Current package via pip & system install throws RuntimeError

### ISSUE THREAD

**Issue by Th3Tr1ckst3r** [chriskiehl/Gooey#870]
- [Window ] OS
 - [Latest] Python Version 
 - [Latest] Gooey Version 

The following error comes from system install via pip with the following command inside of PyCharm:  pip install gooey

```
Collecting gooey
  Using cached Gooey-1.0.8.1-py2.py3-none-any.whl (680 kB)
Requirement already satisfied: Pillow>=4.3.0 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from gooey) (9.4.0)
Collecting psutil>=5.4.2
  Using cached psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
Collecting colored>=1.3.93
  Using cached colored-1.4.4.tar.gz (36 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [26 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Windows\Temp\pip-install-5onurzhu\colored_ec089148750042ea9a441de7e3e2b9d3\setup.py", line 9, in <module>
      setup(
    File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\__init__.py", line 107, in setup
      _install_setup_requires(attrs)
    File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\__init__.py", line 78, in _install_setup_requires
      dist.parse_config_files(ignore_option_errors=True)
    File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\dist.py", line 879, in parse_config_files
      self._parse_config_files(filenames=inifiles)
    File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\dist.py", line 721, in _parse_config_files
      filenames = self.find_config_files()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\_distutils\dist.py", line 338, in find_config_files
      files = [str(path) for path in self._gen_paths() if os.path.isfile(path)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\_distutils\dist.py", line 338, in <listcomp>
      files = [str(path) for path in self._gen_paths() if os.path.isfile(path)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\setuptools\_distutils\dist.py", line 354, in _gen_paths
      yield pathlib.Path('~').expanduser() / filename
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 1385, in expanduser
      raise RuntimeError("Could not determine home directory.")
  RuntimeError: Could not determine home directory.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
 

The following error comes from a system install via pip with the following command:  pip install gooey

```
Collecting gooey
  Using cached Gooey-1.0.8.1-py2.py3-none-any.whl (680 kB)
Requirement already satisfied: Pillow>=4.3.0 in c:\users\administrator\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from gooey) (9.4.0)
Collecting psutil>=5.4.2
  Using cached psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
Collecting colored>=1.3.93
  Using cached colored-1.4.4.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
Collecting pygtrie>=2.3.3
  Using cached pygtrie-2.5.0-py3-none-any.whl (25 kB)
Collecting wxpython>=4.1.0
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-bslwllvz\wxpython_710965f81fdc447992138fb3d2da9642\setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-bslwllvz\wxpython_710965f81fdc447992138fb3d2da9642\buildtools\config.py", line 30, in <module>
          from attrdict import AttrDict
        File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\attrdict\__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\attrdict\mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\collections\__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by MireskaWillow** [comment]
`collections.Mapping` is deprecated and is now `collections.abc.Mapping` in Python 3.10 and newer.
