### ISSUE TITLE
problem with pyinstaller.  'NoneType' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by cmnewfan** [chriskiehl/Gooey#879]
the program works fine when using python command in cmd, but when using pyinstaller, the exe file throws exception.

Traceback (most recent call last):
  File "Model_External_Filed_Test.py", line 212, in <module>
  File "gooey\python_bindings\gooey_decorator.py", line 128, in inner2
  File "Model_External_Filed_Test.py", line 46, in start
  File "gooey\python_bindings\gooey_parser.py", line 125, in parse_args
  File "gooey\python_bindings\gooey_decorator.py", line 123, in run_gooey
  File "gooey\gui\application.py", line 21, in run
  File "gooey\gui\application.py", line 27, in build_app
  File "gooey\gui\application.py", line 40, in _build_app
  File "gooey\gui\containers\application.py", line 47, in __init__
  File "gooey\gui\components\console.py", line 20, in __init__
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "gooey\gui\components\widgets\richtextconsole.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "colored\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "colored\colored.py", line 12, in <module>
AttributeError: 'NoneType' object has no attribute 'isatty'

the line 46 in start is parser.parse_args()

**Comment by keymou** [comment]
> 

I had the same problem, I modified the `colored.py`, Temporarily solved by temporary assignment
```python
try:
    IS_TTY = sys.stdout.isatty() and sys.stderr.isatty()
except AttributeError:
    IS_TTY = False
```
